### ISSUE TITLE
[Bug]: ModuleNotFoundError when installing Pymilvus 2.1.0

### ISSUE THREAD

**Issue by jennyli-z** [milvus-io/pymilvus#1085]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Follow the guide https://milvus.io/docs/v2.1.x/install-pymilvus.md in clean python 3.8.1 environment will get the 
ModuleNotFoundError
```bash
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.8/site-packages/pymilvus/__init__.py", line 13, in <module>
    from .client.stub import Milvus
  File "/usr/local/lib/python3.8/site-packages/pymilvus/client/stub.py", line 3, in <module>
    from .grpc_handler import GrpcHandler
  File "/usr/local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 12, in <module>
    from ..grpc_gen import milvus_pb2_grpc
  File "/usr/local/lib/python3.8/site-packages/pymilvus/grpc_gen/milvus_pb2_grpc.py", line 5, in <module>
    from . import common_pb2 as common__pb2
  File "/usr/local/lib/python3.8/site-packages/pymilvus/grpc_gen/common_pb2.py", line 5, in <module>
    from google.protobuf.internal import enum_type_wrapper
ModuleNotFoundError: No module named 'google'
```

### Expected Behavior

should not failed with error

### Steps/Code To Reproduce behavior

```markdown
docker run -it python:3.8.13-slim-buster /bin/bash
python3 -m pip install pymilvus==2.1.0
python3 -c "from pymilvus import Collection"
```

### Environment details

```markdown
- Hardware/Softward conditions (OS, CPU, GPU, Memory):
- Method of installation (Docker, or from source):
- Milvus version (v0.3.1, or v0.4.0):
- Milvus configuration (Settings you made in `server_config.yaml`):
```

**Comment by jennyli-z** [comment]
fixed on pymilvus-2.1.1 ,close it
