### ISSUE TITLE
[Bug]: pymilvus connection fails with docker container

### ISSUE THREAD

**Issue by OMGMoore** [milvus-io/pymilvus#1216]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I've been troubleshooting this bug with @ZanSara at the Deepset-ai team.

The below error occurs when trying to establish a connection to Milvus from a Docker container, even though a Milvus standalone server is running and connects properly when Docker containers are not used. 

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/pymilvus/client/grpc_handler.py", line 115, in _wait_for_channel_ready
    grpc.channel_ready_future(self._channel).result(timeout=3)
  File "/usr/local/lib/python3.11/site-packages/grpc/_utilities.py", line 139, in result
    self._block(timeout)
  File "/usr/local/lib/python3.11/site-packages/grpc/_utilities.py", line 85, in _block
    raise grpc.FutureTimeoutError()
grpc.FutureTimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/app/src/hello_milvus.py", line 7, in <module>
    connections.connect("default", host="localhost", port="19530")
  File "/usr/local/lib/python3.11/site-packages/pymilvus/orm/connections.py", line 262, in connect
    connect_milvus(**kwargs, password=password)
  File "/usr/local/lib/python3.11/site-packages/pymilvus/orm/connections.py", line 233, in connect_milvus
    gh._wait_for_channel_ready()
  File "/usr/local/lib/python3.11/site-packages/pymilvus/client/grpc_handler.py", line 118, in _wait_for_channel_ready
    raise MilvusException(Status.CONNECT_FAILED, f'Fail connecting to server on {self._address}. Timeout')
pymilvus.exceptions.MilvusException: <MilvusException: (code=2, message=Fail connecting to server on localhost:19530. Timeout)>

```

### Expected Behavior

The connection to the Milvus server will be established without errors.

### Steps/Code To Reproduce behavior

```markdown
Commands used:


docker image build -t python:0.0.1 /home/oliviamga2/TEST/TEST_2
docker run python:0.0.1
```

where the contents of ./TEST/TEST_2 directory are:
1. a dockerfile 
2. .py script that attempts to launch the connection
```
from pymilvus import connections

connections.connect("default", host="localhost", port="19530")
print("connected to Milvus")
```
3. requirements.txt file that installs pymilvus==2.1.0 and protobuf==3.20.0
```


### Environment details

```markdown
- Hardware/Software conditions (OS, CPU, GPU, Memory): Ubuntu 20.04 
- Method of installation (Docker, or from source): Docker 
- Milvus version (v0.3.1, or v0.4.0): 2.1.4 standalone
- Milvus configuration (Settings you made in `server_config.yaml`): n/a
```

**Comment by jonasmeisner** [comment]
I'm having the same problem. Does anyone have an idea how to fix this?

Did you find a workaround @OMGAmici ?

**Comment by OMGAmici** [comment]
@jonasmeisner Unfortunately, I have not been able to find a workaround yet

**Comment by bassemfg** [comment]
I think the problem is the port forwarding does not happen correctly. Here is a workaround that solved this for me:
Run `kubectl port-forward service/my-release-milvus   :19530` 
You will get a result that looks like this: `Forwarding from 127.0.0.1:ABCXYZ -> 19530`
In your python connection code, replace 19530 with ABCXYZ and retry the connection

**Comment by E7ANA** [comment]
same problem here. 
    raise MilvusException(Status.CONNECT_FAILED,
pymilvus.exceptions.MilvusException: <MilvusException: (code=2, message=Fail connecting to server on localhost:19530. Timeout)>

**Comment by caochao18** [comment]
header  grpc to http



---- Replied Message ----
| From | ***@***.***> |
| Date | 04/17/2023 02:19 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [milvus-io/pymilvus] [Bug]: pymilvus connection fails with docker container (Issue #1216) |

same problem here.
raise MilvusException(Status.CONNECT_FAILED,
pymilvus.exceptions.MilvusException: <MilvusException: (code=2, message=Fail connecting to server on localhost:19530. Timeout)>

**Comment by XuanYang-cn** [comment]
Hi, try use the following command to connect docker to the local host network
```shell
docker run --network=host xxxx:xxxx
```

**Comment by XuanYang-cn** [comment]
Here's my test:
```
~/pymilvus_docker/
|- Dockerfile
|- hello_milvus.py
```
**Dockerfile**
```dockerfile
FROM python:3.11

RUN echo "Installing pymilvus ..." && python3 -m pip install pymilvus>=2.2.7

COPY . /app
CMD python /app/hello_milvus.py
```

**hello_milvus.py**
```python
from pymilvus import connections

connections.connect()
print(f"connected to Milvus in addr: {connections.get_connection_addr('default')}")
```

**Commands**
```shell
(~/pymilvus_docker)$ docker build -t pymilvus:latest .
(~/pymilvus_docker)$ docker run --network=host pymilvus:latest
connected to Milvus in addr: {'address': 'localhost:19530', 'user': ''}
```

**Comment by XuanYang-cn** [comment]
@OMGAmici @E7ANA @jonasmeisner Let me know if the suggestion is helpful or not.

**Comment by muktac5** [comment]
Hi @XuanYang-cn we have tried out the suggestions provided, but received the same error.

Can you help us with the step by step approach to set up a pymilvus connection to the milvus server via a docker container?
<img width="1014" alt="Screenshot 2023-05-02 at 7 52 13 PM" src="https://user-images.githubusercontent.com/55969287/235750550-930dc090-adbc-46f0-88ae-4091c0f7d978.png">

**Comment by XuanYang-cn** [comment]
@muktac5 could you provide the result of this command, should be very long if succeed

```
$ docker network inspect milvus
```

**Comment by muktac5** [comment]
This is the response with the `$ docker network inspect `milvus`
<img width="575" alt="github_issue" src="https://user-images.githubusercontent.com/55969287/236186385-9cba22eb-60c7-43e9-8121-afddcc25f7f0.png">

**Comment by XuanYang-cn** [comment]
@muktac5 From the output, seems there're no running containers in your "milvus" network. 
How did you start milvus? are you using this docker-compose.yml here https://milvus.io/docs/install_standalone-docker.md#Download-the-YAML-file?  If not, please provide the docker-compose.yml your're using

Here's what I use, and where the "milvus" network comes from
<img width="1059" alt="image" src="https://user-images.githubusercontent.com/51370125/236367998-909d8096-6103-4e7f-9307-d370f0e8a419.png">

**This is my output of docker network inspect milvus, and the ip in the red box is the ip you need to connect**
<img width="838" alt="image" src="https://user-images.githubusercontent.com/51370125/236368249-a378ffb7-b4ec-408c-9f7a-f4156c8b2909.png">

**Comment by huma23** [comment]
> same problem here. raise MilvusException(Status.CONNECT_FAILED, pymilvus.exceptions.MilvusException: <MilvusException: (code=2, message=Fail connecting to server on localhost:19530. Timeout)>

I had the same issue with connecting from a different container in the docker-compose. In my case I needed to set a _http_proxy_ in the container to do some installation stuff. This proxy blocked the connection to milvus. In the docker-compose file I configured also the _no_proxy_ environment variable with the name of the standalone milvus container. I also added to expose the port of the standalone for other containers. This fixed the connection problem. 

Maybe this setup will help you (docker-compose.yml):

```
version: '3.5'

services:
  etcd:
    ...

  minio:
    ...

  standalone:
    container_name: milvus-standalone
    image: milvusdb/milvus:v2.2.8
    command: ["milvus", "run", "standalone"]
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/data/index/milvus:/var/lib/milvus
    expose:
      - "19530"
    depends_on:
      - "etcd"
      - "minio"
     
  my-test-service:
    container_name: my-test-service
    build:
      dockerfile: ./Dockerfile
      args:
        - http_proxy=$http_proxy
    environment:
      no_proxy: milvus-standalone,localhost,127.0.0.1,0.0.0.0
```

**Comment by muktac5** [comment]
yes @XuanYang-cn am using the docker-compose.yml from here https://milvus.io/docs/install_standalone-docker.md#Download-the-YAML-file. sorry shared the docker network inspect milvus output prior to starting the containers. sharing the updated one. also tried to connect to the IP of the milvus-standalone container but got the same error.

docker-compose.yml
<img width="844" alt="Screenshot 2023-05-05 at 11 15 01 PM" src="https://user-images.githubusercontent.com/55969287/236532117-2a3f2615-f290-492f-9dca-0cf7f21f35b8.png">

`docker network inspect milvus`
<img width="692" alt="Screenshot 2023-05-05 at 11 18 56 PM" src="https://user-images.githubusercontent.com/55969287/236532218-21db7124-a54c-4a79-8165-f9c4e0db5c24.png">

Connection error
<img width="995" alt="Screenshot 2023-05-05 at 11 24 42 PM" src="https://user-images.githubusercontent.com/55969287/236532372-c85dc4d5-9277-4492-8bb3-62881ba7024a.png">
