### ISSUE TITLE
[Bug]: There is an error with max_length

### ISSUE THREAD

**Issue by kongbo96** [milvus-io/pymilvus#1320]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

![image](https://user-images.githubusercontent.com/42367656/222624671-f055d6be-8f30-4ad3-a21f-897ef1e0d9ef.png)

![image](https://user-images.githubusercontent.com/42367656/222624731-572a41ae-574b-464f-9669-1975756425f3.png)

The length of “query“” column data cannot be greater than 10, but the length of “t_deadline_ts“ column data can be greater than 10.

It's ridiculous.

### Environment details

```markdown
pymilvus 2.2.1
milvus2.1.4
```

**Comment by pikaduck** [comment]
@kongbo96 Milvus had a bug in versions 2.2.x wherein the function check_insert_data_schema() was using the max_length of the field x-1 for field x, thus len(t_deadline_ts) was being compared with 32, i.e., max_length(t_id) & len(query) was being compared with max_length(t_deadline_ts), i.e., 10. If you upgrade pymilvus to 2.3.x, this issue has been resolved and the new func is called check_insert_or_upsert_data_schema. My guess is that this was happening because they were passing the correct entity but they forgot to not send field_info of the first field, i.e., the auto_id if it was used by you in the schema

**Comment by kongbo96** [comment]
Thank you for your reply. @pikaduck

**Comment by kongbo96** [comment]
I ran into another error using version 2.3.0b1 of pymilvus.

> RPC error: [load_collection], <MilvusException: (code=1, message=<_MultiThreadedRendezvous of RPC that terminated with:
> 		status = StatusCode.UNIMPLEMENTED
> 		details = "unknown method GetLoadingProgress for service milvus.proto.milvus.MilvusService"
> 		debug_error_string = "{"created":"@1683518503.893589422","description":"Error received from peer ipv4:172.20.62.135:19530","file":"src/core/lib/surface/call.cc","file_line":966,"grpc_message":"unknown method GetLoadingProgress for service milvus.proto.milvus.MilvusService","grpc_status":12}"
> 	>)>, <Time:{'RPC start': '2023-05-08 12:01:43.880126', 'RPC error': '2023-05-08 12:01:43.894005'}>
> 	Traceback (most recent call last):
> 	  File "/root/miniconda3/envs/nlp/lib/python3.8/site-packages/pymilvus/decorators.py", line 50, in handler
> 	    return func(self, *args, **kwargs)
> 	  File "/root/miniconda3/envs/nlp/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 793, in get_loading_progress
> 	    response = self._stub.GetLoadingProgress.future(request, timeout=timeout).result()
> 	  File "/root/miniconda3/envs/nlp/lib/python3.8/site-packages/grpc/_channel.py", line 744, in result
> 	    raise self
> 	grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
> 		status = StatusCode.UNIMPLEMENTED
> 		details = "unknown method GetLoadingProgress for service milvus.proto.milvus.MilvusService"
> 		debug_error_string = "{"created":"@1683518503.893589422","description":"Error received from peer ipv4:172.20.62.135:19530","file":"src/core/lib/surface/call.cc","file_line":966,"grpc_message":"unknown method GetLoadingProgress for service milvus.proto.milvus.MilvusService","grpc_status":12}"
> 	>
> 	
> 	The above exception was the direct cause of the following exception:
> 	
> 	Traceback (most recent call last):
> 	  File "to_milvus.py", line 86, in <module>
> 	    main()
> 	  File "to_milvus.py", line 83, in main
> 	    collection.load()
> 	  File "/root/miniconda3/envs/nlp/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 366, in load
> 	    conn.load_collection(self._name, replica_number=replica_number, timeout=timeout, **kwargs)
> 	  File "/root/miniconda3/envs/nlp/lib/python3.8/site-packages/pymilvus/decorators.py", line 109, in handler
> 	    raise e
> 	  File "/root/miniconda3/envs/nlp/lib/python3.8/site-packages/pymilvus/decorators.py", line 105, in handler
> 	    return func(*args, **kwargs)
> 	  File "/root/miniconda3/envs/nlp/lib/python3.8/site-packages/pymilvus/decorators.py", line 136, in handler
> 	    ret = func(self, *args, **kwargs)
> 	  File "/root/miniconda3/envs/nlp/lib/python3.8/site-packages/pymilvus/decorators.py", line 85, in handler
> 	    raise e
> 	  File "/root/miniconda3/envs/nlp/lib/python3.8/site-packages/pymilvus/decorators.py", line 50, in handler
> 	    return func(self, *args, **kwargs)
> 	  File "/root/miniconda3/envs/nlp/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 710, in load_collection
> 	    self.wait_for_loading_collection(collection_name, timeout)
> 	  File "/root/miniconda3/envs/nlp/lib/python3.8/site-packages/pymilvus/decorators.py", line 109, in handler
> 	    raise e
> 	  File "/root/miniconda3/envs/nlp/lib/python3.8/site-packages/pymilvus/decorators.py", line 105, in handler
> 	    return func(*args, **kwargs)
> 	  File "/root/miniconda3/envs/nlp/lib/python3.8/site-packages/pymilvus/decorators.py", line 136, in handler
> 	    ret = func(self, *args, **kwargs)
> 	  File "/root/miniconda3/envs/nlp/lib/python3.8/site-packages/pymilvus/decorators.py", line 85, in handler
> 	    raise e
> 	  File "/root/miniconda3/envs/nlp/lib/python3.8/site-packages/pymilvus/decorators.py", line 50, in handler
> 	    return func(self, *args, **kwargs)
> 	  File "/root/miniconda3/envs/nlp/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 728, in wait_for_loading_collection
> 	    progress = self.get_loading_progress(collection_name, timeout=timeout)
> 	  File "/root/miniconda3/envs/nlp/lib/python3.8/site-packages/pymilvus/decorators.py", line 109, in handler
> 	    raise e
> 	  File "/root/miniconda3/envs/nlp/lib/python3.8/site-packages/pymilvus/decorators.py", line 105, in handler
> 	    return func(*args, **kwargs)
> 	  File "/root/miniconda3/envs/nlp/lib/python3.8/site-packages/pymilvus/decorators.py", line 136, in handler
> 	    ret = func(self, *args, **kwargs)
> 	  File "/root/miniconda3/envs/nlp/lib/python3.8/site-packages/pymilvus/decorators.py", line 56, in handler
> 	    raise MilvusException(message=str(e)) from e
> 	pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=<_MultiThreadedRendezvous of RPC that terminated with:
> 		status = StatusCode.UNIMPLEMENTED
> 		details = "unknown method GetLoadingProgress for service milvus.proto.milvus.MilvusService"
> 		debug_error_string = "{"created":"@1683518503.893589422","description":"Error received from peer ipv4:172.20.62.135:19530","file":"src/core/lib/surface/call.cc","file_line":966,"grpc_message":"unknown method GetLoadingProgress for service milvus.proto.milvus.MilvusService","grpc_status":12}"
> 	>)>
> [INFO] 2023-05-08 12:01:44.166 [TaskLogInfo- - [taskAppId=TASK-9009632155584_5-286484-583073]-getOutputLogService]  - FINALIZE_SESSION
>

**Comment by pikaduck** [comment]
Is your collection spread across partitions?
