### ISSUE TITLE
[Bug]: Failed to get the same collection even passed the same schema

### ISSUE THREAD

**Issue by yah01** [milvus-io/pymilvus#1450]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The error reported while I run a script twice:
```
Traceback (most recent call last):
  File "/home/yah01/src/milvus/test.py", line 20, in <module>
    collection = Collection("test_search_collection_multiple_json_0", schema=schema)
  File "/home/yah01/miniconda3/lib/python3.10/site-packages/pymilvus/orm/collection.py", line 110, in __init__
    raise SchemaNotReadyException(message=ExceptionsMessage.SchemaInconsistent)
pymilvus.exceptions.SchemaNotReadyException: <SchemaNotReadyException: (code=1, message=The collection already exist, but the schema is not the same as the schema passed in.)>
```

### Environment details

```markdown
- Hardware/Softward conditions (OS, CPU, GPU, Memory):
- Method of installation (Docker, or from source):
- Milvus version (v0.3.1, or v0.4.0):
- Milvus configuration (Settings you made in `server_config.yaml`):
```

**Comment by yah01** [comment]
After test, it's introduced since 5a581ce6097f36b20687f5aeb988db82ac6212e9
