### ISSUE TITLE
[Bug]: [High level] Shall we not set  "None" as default value for Parameter "filter" in milvus_client.query 

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/pymilvus#1525]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Parameter "filter" in milvus_client.query should not have default value:

when typing milvus_client.query("binbin_milvus"), it reports
```
TypeError: query() missing 1 required positional argument: 'collection_name'
```
and when typing "milvus_client.query(collection_name="binbin_milvus")", it reports:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/milvus_client/milvus_client.py", line 277, in query
    raise DataTypeNotMatchException(message=ExceptionsMessage.ExprType % type(filter))
pymilvus.exceptions.DataTypeNotMatchException: <DataTypeNotMatchException: (code=1, message=The type of expr must be string ,but <class 'NoneType'> is given.)>
```

Why it will report error as None is the default value.

### Expected Behavior

1. did not set default value for filter, then it could tell users there are 2 parameters are needed

OR

2. set a excutable default value for filter

### Steps/Code To Reproduce behavior

```markdown
Only query with collection name, do not input value for parameter "filter"

milvus_client.query("binbin_milvus")
```

### Environment details

```markdown
- Hardware/Softward conditions (OS, CPU, GPU, Memory):
- Method of installation (Docker, or from source):
- Milvus version (v0.3.1, or v0.4.0):
- Milvus configuration (Settings you made in `server_config.yaml`):
```

### Anything else?

pymilvus: 2.2.10.dev1
milvus: 2.2.0-20230607-02e3b06b

**Comment by binbinlv** [comment]
Now, will report errror, but the error message seems not very meaningful:

```
>>> milvus_client.query("milvus_client_api_alias_kxmKVlJg")
RPC error: [query], <MilvusException: (code=65535, message=empty expression should be used with limit)>, <Time:{'RPC start': '2024-01-25 11:54:36.360605', 'RPC error': '2024-01-25 11:54:36.447364'}>
Failed to query collection: milvus_client_api_alias_kxmKVlJg
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 393, in query
    raise ex from ex
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 383, in query
    res = conn.query(
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 135, in handler
    raise e from e
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 131, in handler
    return func(*args, **kwargs)
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 170, in handler
    return func(self, *args, **kwargs)
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 110, in handler
    raise e from e
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 74, in handler
    return func(*args, **kwargs)
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 1431, in query
    check_status(response.status)
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/client/utils.py", line 60, in check_status
    raise MilvusException(status.code, status.reason, status.error_code)
pymilvus.exceptions.MilvusException: <MilvusException: (code=65535, message=empty expression should be used with limit)>
```

And the query should be successfully input either limit or filter, so I think the message "params filter or limit should be not empty" could be better 
```
>>> milvus_client.query("milvus_client_api_alias_kxmKVlJg", limit=2)
[]
>>>
>>>
>>> milvus_client.query("milvus_client_api_alias_kxmKVlJg", filter="id > 0")
[]
```

**Comment by binbinlv** [comment]
Verified and fixed:
pymilvus: 2.4.0rc30
milvus: master-20240205-a68b3213

results:
```
>>> milvus_client.query(collection_name="binbin_milvus")
RPC error: [query], <MilvusException: (code=65535, message=empty expression should be used with limit)>, <Time:{'RPC start': '2024-02-05 15:01:13.856428', 'RPC error': '2024-02-05 15:01:13.936838'}>
Failed to query collection: binbin_milvus
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 416, in query
    raise ex from ex
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 406, in query
    res = conn.query(
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 135, in handler
    raise e from e
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 131, in handler
    return func(*args, **kwargs)
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 170, in handler
    return func(self, *args, **kwargs)
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 110, in handler
    raise e from e
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 74, in handler
    return func(*args, **kwargs)
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 1432, in query
    check_status(response.status)
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/client/utils.py", line 60, in check_status
    raise MilvusException(status.code, status.reason, status.error_code)
pymilvus.exceptions.MilvusException: <MilvusException: (code=65535, message=empty expression should be used with limit)>
```
