### ISSUE TITLE
[Bug]: Username and password errors occurred in MilvusClient. describe_collection

### ISSUE THREAD

**Issue by qixuan0212** [milvus-io/pymilvus#1544]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When I access zilliz cloud with milvusclient，Username and password errors occurred in MilvusClient. describe_collection。
Follow the following method：https://docs.zilliz.com/reference/describe_collection
pymilvus：2.2.11
I make sure the username and password were correct。
my code is：
`from pymilvus import MilvusClient

uri = 'https://in01-355ba64c1753e43.aws-us-west-2.vectordb.zillizcloud.com:19533'
token = 'db_admin:****'
client = MilvusClient(uri, token)

client.describe_collection(collection_name='medium_articles')`

### Expected Behavior

success to get the result of describe_collection.

### Environment details

```markdown
- Hardware/Softward conditions (OS, CPU, GPU, Memory):
- Method of installation (Docker, or from source):
- Milvus version (v0.3.1, or v0.4.0):
- Milvus configuration (Settings you made in `server_config.yaml`):
```

### Anything else?

error info is:
`RPC error: [__internal_register], <MilvusException: (code=1, message=<_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "auth check failure, please check username and password are correct"
	debug_error_string = "UNKNOWN:Error received from peer ipv4:54.69.43.77:19533 {created_time:"2023-06-16T16:38:01.806097+08:00", grpc_status:2, grpc_message:"auth check failure, please check username and password are correct"}"
>)>, <Time:{'RPC start': '2023-06-16 16:38:01.262009', 'RPC error': '2023-06-16 16:38:01.809624'}>
Failed to create new connection using: 668a0432c4de4e7dbfa6dff551237ed7
Traceback (most recent call last):
  File "/Users/qixuan02/Library/Python/3.8/lib/python/site-packages/pymilvus/decorators.py", line 50, in handler
    return func(self, *args, **kwargs)
  File "/Users/qixuan02/Library/Python/3.8/lib/python/site-packages/pymilvus/decorators.py", line 169, in handler
    raise e
  File "/Users/qixuan02/Library/Python/3.8/lib/python/site-packages/pymilvus/decorators.py", line 163, in handler
    return func(*args, **kwargs)
  File "/Users/qixuan02/Library/Python/3.8/lib/python/site-packages/pymilvus/client/grpc_handler.py", line 1359, in __internal_register
    response = self._stub.Connect(request=req)
  File "/Users/qixuan02/Library/Python/3.8/lib/python/site-packages/grpc/_interceptor.py", line 247, in __call__
    response, ignored_call = self._with_call(request,
  File "/Users/qixuan02/Library/Python/3.8/lib/python/site-packages/grpc/_interceptor.py", line 290, in _with_call
    return call.result(), call
  File "/Users/qixuan02/Library/Python/3.8/lib/python/site-packages/grpc/_channel.py", line 379, in result
    raise self
  File "/Users/qixuan02/Library/Python/3.8/lib/python/site-packages/grpc/_interceptor.py", line 274, in continuation
    response, call = self._thunk(new_method).with_call(
  File "/Users/qixuan02/Library/Python/3.8/lib/python/site-packages/grpc/_channel.py", line 1043, in with_call
    return _end_unary_response_blocking(state, call, True, None)
  File "/Users/qixuan02/Library/Python/3.8/lib/python/site-packages/grpc/_channel.py", line 910, in _end_unary_response_blocking
    raise _InactiveRpcError(state)  # pytype: disable=not-instantiable
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "auth check failure, please check username and password are correct"
	debug_error_string = "UNKNOWN:Error received from peer ipv4:54.69.43.77:19533 {created_time:"2023-06-16T16:38:01.806097+08:00", grpc_status:2, grpc_message:"auth check failure, please check username and password are correct"}"
>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/qixuan02/Library/Python/3.8/lib/python/site-packages/pymilvus/client/grpc_handler.py", line 120, in _wait_for_channel_ready
    self._setup_identifier_interceptor(self._user)
  File "/Users/qixuan02/Library/Python/3.8/lib/python/site-packages/pymilvus/client/grpc_handler.py", line 220, in _setup_identifier_interceptor
    self._identifier = self.__internal_register(user, host)
  File "/Users/qixuan02/Library/Python/3.8/lib/python/site-packages/pymilvus/decorators.py", line 109, in handler
    raise e
  File "/Users/qixuan02/Library/Python/3.8/lib/python/site-packages/pymilvus/decorators.py", line 105, in handler
    return func(*args, **kwargs)
  File "/Users/qixuan02/Library/Python/3.8/lib/python/site-packages/pymilvus/decorators.py", line 136, in handler
    ret = func(self, *args, **kwargs)
  File "/Users/qixuan02/Library/Python/3.8/lib/python/site-packages/pymilvus/decorators.py", line 56, in handler
    raise MilvusException(message=str(e)) from e
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=<_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "auth check failure, please check username and password are correct"
	debug_error_string = "UNKNOWN:Error received from peer ipv4:54.69.43.77:19533 {created_time:"2023-06-16T16:38:01.806097+08:00", grpc_status:2, grpc_message:"auth check failure, please check username and password are correct"}"
>)>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "1.py", line 5, in <module>
    client = MilvusClient(uri, token)
  File "/Users/qixuan02/Library/Python/3.8/lib/python/site-packages/pymilvus/milvus_client/milvus_client.py", line 56, in __init__
    self._using = self._create_connection(uri, user, password, db_name, token, **kwargs)
  File "/Users/qixuan02/Library/Python/3.8/lib/python/site-packages/pymilvus/milvus_client/milvus_client.py", line 523, in _create_connection
    raise ex
  File "/Users/qixuan02/Library/Python/3.8/lib/python/site-packages/pymilvus/milvus_client/milvus_client.py", line 518, in _create_connection
    connections.connect(using, user, password, db_name, token, uri=uri, **kwargs)
  File "/Users/qixuan02/Library/Python/3.8/lib/python/site-packages/pymilvus/orm/connections.py", line 349, in connect
    connect_milvus(**kwargs, user=user, password=password, token=token, db_name=db_name)
  File "/Users/qixuan02/Library/Python/3.8/lib/python/site-packages/pymilvus/orm/connections.py", line 282, in connect_milvus
    gh._wait_for_channel_ready(timeout=timeout)
  File "/Users/qixuan02/Library/Python/3.8/lib/python/site-packages/pymilvus/client/grpc_handler.py", line 123, in _wait_for_channel_ready
    raise MilvusException(Status.CONNECT_FAILED,
pymilvus.exceptions.MilvusException: <MilvusException: (code=2, message=Fail connecting to server on in01-355ba64c1753e43.aws-us-west-2.vectordb.zillizcloud.com:19533. Timeout)>`

**Comment by czs007** [comment]
hi @qixuan0212 
please try 
```
token = 'db_admin:****'
client = MilvusClient(uri, token=token)
```

```
class MilvusClient:
    def __init__(self,
                 uri: str = "http://localhost:19530",
                 user: str = "",
                 password: str = "",
                 db_name: str = "",
                 token: str = "",
                 timeout: float = None, **kwargs):
```

In Python, keyword arguments are a way of passing arguments to a function that allows the caller to use parameter names to specify arguments instead of passing them in the order they appear in the function definition.
