### ISSUE TITLE
[Bug]: Timeout occurs when make connection to zilliz

### ISSUE THREAD

**Issue by tuvshinbay4r** [milvus-io/pymilvus#1570]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When I run `hello_zilliz_vectordb_serverless.py`, it fails
```bash
raceback (most recent call last):
  File "/opt/anaconda3/envs/milvus/lib/python3.11/site-packages/pymilvus/client/grpc_handler.py", line 119, in _wait_for_channel_ready
    grpc.channel_ready_future(self._channel).result(timeout=timeout)
  File "/opt/anaconda3/envs/milvus/lib/python3.11/site-packages/grpc/_utilities.py", line 151, in result
    self._block(timeout)
  File "/opt/anaconda3/envs/milvus/lib/python3.11/site-packages/grpc/_utilities.py", line 97, in _block
    raise grpc.FutureTimeoutError()
grpc.FutureTimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/giva/Downloads/cloud-vectordb-examples/python/hello_zilliz_vectordb_serverless.py", line 15, in <module>
    connections.connect("default",
  File "/opt/anaconda3/envs/milvus/lib/python3.11/site-packages/pymilvus/orm/connections.py", line 349, in connect
    connect_milvus(**kwargs, user=user, password=password, token=token, db_name=db_name)
  File "/opt/anaconda3/envs/milvus/lib/python3.11/site-packages/pymilvus/orm/connections.py", line 282, in connect_milvus
    gh._wait_for_channel_ready(timeout=timeout)
  File "/opt/anaconda3/envs/milvus/lib/python3.11/site-packages/pymilvus/client/grpc_handler.py", line 123, in _wait_for_channel_ready
    raise MilvusException(Status.CONNECT_FAILED,
pymilvus.exceptions.MilvusException: <MilvusException: (code=2, message=Fail connecting to server on in03-c2a35ceefea6832.api.gcp-us-west1.zillizcloud.com:443. Timeout)>
```

### Expected Behavior

It should work fine, as mention in the zilliz documentation.
when I make request using curl like this
```bash
curl --request GET \                                                                                                                                                                                     ✭
  --url https://in03-ascx1231231.api.gcp-us-west1.zillizcloud.com/v1/vector/collections \
  --header 'accept: application/json' \
  --header 'authorization: Bearer <token>'
```
It works and gives me
```bash
{"code":200,"data":[]}
```

### Steps/Code To Reproduce behavior

1. `conda create -n milvus python=3.11`
2. `git clone https://github.com/zilliztech/cloud-vectordb-examples.git`
3. `conda activate milvus`
4. `pip install pymilvus==2.2.11`
5. `cd cloud-vectordb-examples`
6. `cd python`
7. Modify uri, token in the configuration file.(config_serverless.ini)
8. `python hello_zilliz_vectordb_serverless.py`

### Environment details

```markdown
- Hardware/Softward conditions (MacOS, 10 core, 16 core, 64GB):
- Method of installation (from source):
```

**Comment by SamSamhuns** [comment]
Have you tried increasing the `timeout` parameter when connecting to zilliz cloud

```
 connections.connect(
     alias="default",
     uri='zilliz url',
     secure=True,
     user='uname',
     password='pass',
     timeout=120
 )
```

**Comment by giva9712** [comment]
Sorry, my bad.
I should have added my IP address to the whitelist of zilliz cloud.

**Comment by tuvshinbay4r** [comment]
Sorry, my bad.
I should have added my IP address to the whitelist of zilliz cloud.

**Comment by tuvshinbay4r** [comment]
Sorry, my bad.
I should have added my IP address to the whitelist of zilliz cloud.
