### ISSUE TITLE
[FEATURE]: How to add read and write permissions for a partition to a user？

### ISSUE THREAD

**Issue by become-nice** [milvus-io/pymilvus#1650]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

&emsp;&emsp;In the milvus [document](https://milvus.io/docs/users_and_roles.md), milvus can support partition-level user read and write permission settings, but in fact I can’t set it. May I ask whether it currently does not support partition-level read and write permission settings or the method I used is wrong.The method I use is as follows.

```python
from pymilvus import (
    connections,
    utility, Role,
    FieldSchema, CollectionSchema, DataType,
    Collection,
)

if __name__ == '__main__':
    connections.connect(host="xx.xx.xx.xx", port="19530",user="root",password="yyyyyy")
 
    # utility.create_user("user2", "testforpartition")
    role = Role("guset")
    # role.add_user("user2")
    role.grant("Partition", "MultiPartitionTest_partition1", "Query")
```
&emsp;&emsp;The error message is as follows.

```python
RPC error: [grant_privilege], <MilvusException: (code=41, message=not found the object type[name: Partition], supported the object types: [User Collection Global])>, <Time:{'RPC start': '2023-08-18 11:13:39.491542', 'RPC error': '2023-08-18 11:13:39.493285'}>
Traceback (most recent call last):
  File "/home/liupeng13/milvus/create_role.py", line 14, in <module>
    role.grant("Partition", "MultiPartitionTest_partition1", "Query")
  File "/home/liupeng13/.local/lib/python3.11/site-packages/pymilvus/orm/role.py", line 150, in grant
    return self._get_connection().grant_privilege(self._name, object, object_name, privilege)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/liupeng13/.local/lib/python3.11/site-packages/pymilvus/decorators.py", line 109, in handler
    raise e
  File "/home/liupeng13/.local/lib/python3.11/site-packages/pymilvus/decorators.py", line 105, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/liupeng13/.local/lib/python3.11/site-packages/pymilvus/decorators.py", line 136, in handler
    ret = func(self, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/liupeng13/.local/lib/python3.11/site-packages/pymilvus/decorators.py", line 85, in handler
    raise e
  File "/home/liupeng13/.local/lib/python3.11/site-packages/pymilvus/decorators.py", line 50, in handler
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/liupeng13/.local/lib/python3.11/site-packages/pymilvus/client/grpc_handler.py", line 1181, in grant_privilege
    raise MilvusException(resp.error_code, resp.reason)
pymilvus.exceptions.MilvusException: <MilvusException: (code=41, message=not found the object type[name: Partition], supported the object types: [User Collection Global])>
```
&emsp;&emsp;I also tried the Collection parameter, also can't get it to set.

**Comment by XuanYang-cn** [comment]
@become-nice Milvus doesn't support partition-level rbac, the minimum level is Collection.

As for collection level rpac, try to create the role before grant a privilege
```
    role = Role(role_name, using=_CONNECTION)
    print(f"create role, role_name: {role_name}")
    role.create()
```

here's a example may help: https://github.com/milvus-io/pymilvus/blob/5a685eb02724c57786e0e9cbe1cca960678c8ec3/examples/role_and_privilege.py#L170
