### ISSUE TITLE
[QUESTION]: IndexError: list index out of range

### ISSUE THREAD

**Issue by djswagerman** [milvus-io/pymilvus#1684]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What is your question?

When following the "getting started" at https://milvus.io/docs/insert_data.md, I received the following error:

mr = collection.insert(data)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/homebrew/lib/python3.11/site-packages/pymilvus/orm/collection.py", line 495, in insert
    check_insert_schema(self._schema, data)
  File "/opt/homebrew/lib/python3.11/site-packages/pymilvus/orm/schema.py", line 406, in check_insert_schema
    infer_fields, tmp_fields, is_data_frame = parse_fields_from_data(schema, data)
                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pymilvus/orm/schema.py", line 452, in parse_fields_from_data
    fields = FieldSchema("", infer_dtype_bydata(data[index][0]))
                                                ~~~~~~~~~~~^^^
IndexError: list index out of range


This is the collection.schema;
{'auto_id': False, 'description': 'Test book search', 'fields': [{'name': 'book_id', 'description': '', 'type': <DataType.INT64: 5>, 'is_primary': True, 'auto_id': False}, {'name': 'book_name', 'description': '', 'type': <DataType.VARCHAR: 21>, 'params': {'max_length': 200}}, {'name': 'word_count', 'description': '', 'type': <DataType.INT64: 5>}, {'name': 'book_intro', 'description': '', 'type': <DataType.FLOAT_VECTOR: 101>, 'params': {'dim': 2}}], 'enable_dynamic_field': True}

And the data was created using https://milvus.io/docs/create_collection.md

Are the code and the "Getting started" perhaps not in sync anymore? What could I further try?

### Anything else?

I run on a MacBook Pro m2

**Comment by noodlesLJH** [comment]
i met this too, on linux.
