### ISSUE TITLE
[Bug]: Handshake failed with fatal error SSL_ERROR_SSL: error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER.

### ISSUE THREAD

**Issue by brandonbiggs** [milvus-io/pymilvus#1706]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I follow the documentation to connect to Milvus with pymilvus via TLS and run into this issue. Here's the documentation I'm following - https://milvus.io/docs/tls.md#Connect-to-the-Milvus-server-with-TLS

This seems to have different kwargs than the examples further down the page.
```client_pem_path="cert/client.pem",
                        client_key_path="cert/client.key",
                        ca_pem_path="cert/ca.pem",
```
The [example](https://github.com/milvus-io/pymilvus/blob/master/examples/example_tls1.py) shows `server_pem_path` rather than `client_pem_path`.

[Example 2](https://github.com/milvus-io/pymilvus/blob/master/examples/example_tls2.py) shows `client_pem_path`. 

Regardless of which one I use, I still get the error - `Handshake failed with fatal error SSL_ERROR_SSL: error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER.`

### Expected Behavior

I would expect that I could connect via TLS.

### Steps/Code To Reproduce behavior

```markdown
Follow the documentation. Configure the `tls:` and `common-security` section of milvus.yaml.
```

### Environment details

```markdown
- Hardware/Softward conditions (OS, CPU, GPU, Memory): Host OS Ubuntu 20.04, Intel CPU, Nvidia GPU, ~500GB Memory
- Method of installation (Docker, or from source): Docker compose
- Milvus version (v0.3.1, or v0.4.0): milvusdb/milvus:v2.3.0
- Milvus configuration (Settings you made in `server_config.yaml`):

This only shows the changes I made from the default milvus.yaml that the documentation provides

tls:
  serverPemPath: /path/to/my/server.crt    
  serverKeyPath: /path/to/my/server.key
  caPemPath: /path/to/my/ca.crt
common:
  security:
    authorizationEnabled: true
    superUsers: root
```
```


### Anything else?

If I remove `secure=True` from the `connections.connect()` kwargs, then I am able to connect. As soon as I put `secure=True` I get errors.

**Comment by brandonbiggs** [comment]
I did a bunch of searching before posting this, and then finally found something basically right after I posted this. [Another question](https://github.com/milvus-io/pymilvus/issues/1321) led me to make one additional change in my milvus.yaml file
```
common:
  security:
    authorizationEnabled: true
    superUsers: root
    tlsMode: 1
```
Once I made this change I could set `secure=True` and then connect. 

I didn't see anything about this setting in the documentation. Did I miss that? I searched the documentation for the `tlsMode` parameter and didn't see anything?

**Comment by brandonbiggs** [comment]
Thanks @SimFG . The issue was really that I couldn't find that in the documentation. Maybe that exists, but I couldn't find that `tlsMode=` needed to be something in my milvus.yaml.

**Comment by nchanmala** [comment]
I ran into the same issue trying to setup TLS on docker standalone.  I also could not find tlsMode= on the .yaml either.


[milvus@redacted_hostname ~]$ python connectssl.py

Create connection...
E0415 13:48:26.135982240 2972465 ssl_transport_security.cc:1511]       Handshake failed with fatal error SSL_ERROR_SSL: error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER.
E0415 13:48:27.135478291 2972465 ssl_transport_security.cc:1511]       Handshake failed with fatal error SSL_ERROR_SSL: error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER.
E0415 13:48:28.845451891 2972465 ssl_transport_security.cc:1511]       Handshake failed with fatal error SSL_ERROR_SSL: error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER.
E0415 13:48:31.033768538 2972465 ssl_transport_security.cc:1511]       Handshake failed with fatal error SSL_ERROR_SSL: error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER.
E0415 13:48:35.539850318 2972465 ssl_transport_security.cc:1511]       Handshake failed with fatal error SSL_ERROR_SSL: error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER.
Traceback (most recent call last):
  File "/home/milvus/.local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 143, in _wait_for_channel_ready
    grpc.channel_ready_future(self._channel).result(timeout=timeout)
  File "/home/milvus/.local/lib/python3.8/site-packages/grpc/_utilities.py", line 162, in result
    self._block(timeout)
  File "/home/milvus/.local/lib/python3.8/site-packages/grpc/_utilities.py", line 106, in _block
    raise grpc.FutureTimeoutError()
grpc.FutureTimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "connectssl.py", line 7, in <module>
    connections.connect(host=_HOST, port=_PORT, secure=True, client_pem_path="/opt/tools/volumes/milvus_home/configs/cert/client.pem",
  File "/home/milvus/.local/lib/python3.8/site-packages/pymilvus/orm/connections.py", line 420, in connect
    connect_milvus(**kwargs, user=user, password=password, token=token, db_name=db_name)
  File "/home/milvus/.local/lib/python3.8/site-packages/pymilvus/orm/connections.py", line 371, in connect_milvus
    gh._wait_for_channel_ready(timeout=timeout)
  File "/home/milvus/.local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 146, in _wait_for_channel_ready
    raise MilvusException(
pymilvus.exceptions.MilvusException: <MilvusException: (code=2, message=Fail connecting to server on redacted_hostname:19530, illegal connection params or server unavailable)>

**Comment by nchanmala** [comment]
I also tried both 1 way and 2 ways and no success.  The only way I can made it connect was to remove the "Secure=True" off my connection script.

Here is my setting:


# Configure the proxy tls enable.
tls:
  serverPemPath: /opt/tools/volumes/milvus_home/configs/cert/server.pem
  serverKeyPath: /opt/tools/volumes/milvus_home/configs/cert/server.key
  caPemPath: /opt/tools/volumes/milvus_home/configs/cert/ca.pem

common:
   security:
    authorizationEnabled: true
    # The superusers will ignore some system check processes,
    # like the old password verification when updating the credential
    superUsers: root
    tlsMode: 1

**Comment by sourabh-bootnext** [comment]
@jaime0815 any update on this? I'm also facing same issue. i want to run milvus with tls. @nchanmala you get any solution to run it?

**Comment by nchanmala** [comment]
thanks . Yep! I am all set!
