### ISSUE TITLE
[Bug]: test_local_writer_npy function in example_bulkwriter.py  do not support writing int64 to local npy files

### ISSUE THREAD

**Issue by qixuan0212** [milvus-io/pymilvus#1710]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

1. autoid of field id in build_csv_collection is set to false
2. train_embeddings.csv in data add a column of id
3. run test_local_writer_npy in example_bulkwriter.py, error occurred.

`ERROR:bulk_writer:Illegal scalar value for field 'INT64', value overflow or type mismatch
INFO:local_bulk_writer:Delete empty directory '/tmp/bulk_writer/781c92f5-dd80-42df-bfdd-1a34d51120fd'
Traceback (most recent call last):
  File "/Users/zilliz/qixuan/GitHub/pymilvus/examples/example_bulkwriter.py", line 361, in <module>
    test_local_writer_npy(schema)
  File "/Users/zilliz/qixuan/GitHub/pymilvus/examples/example_bulkwriter.py", line 138, in test_local_writer_npy
    read_sample_data("./data/train_embeddings.csv", local_writer)
  File "/Users/zilliz/qixuan/GitHub/pymilvus/examples/example_bulkwriter.py", line 114, in read_sample_data
    writer.append_row(row)
  File "/Users/zilliz/qixuan/GitHub/pymilvus/pymilvus/bulk_writer/local_bulk_writer.py", line 84, in append_row
    super().append_row(row, **kwargs)
  File "/Users/zilliz/qixuan/GitHub/pymilvus/pymilvus/bulk_writer/bulk_writer.py", line 75, in append_row
    self._verify_row(row)
  File "/Users/zilliz/qixuan/GitHub/pymilvus/pymilvus/bulk_writer/bulk_writer.py", line 141, in _verify_row
    self._throw(
  File "/Users/zilliz/qixuan/GitHub/pymilvus/pymilvus/bulk_writer/bulk_writer.py", line 90, in _throw
    raise MilvusException(message=msg)
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=Illegal scalar value for field 'INT64', value overflow or type mismatch)>`

### Expected Behavior

test_local_writer_npy function in example_bulkwriter.py support writing int64 to local npy files

### Steps/Code To Reproduce behavior

```markdown
1. autoid of field id in build_csv_collection is set to false
2. train_embeddings.csv in data add a column of id
3. run test_local_writer_npy in example_bulkwriter.py, error occurred.
```

### Environment details

```markdown
- Hardware/Softward conditions (OS, CPU, GPU, Memory):
- Method of installation (Docker, or from source):
- Milvus version (v0.3.1, or v0.4.0): 2.2
- Milvus configuration (Settings you made in `server_config.yaml`):
```

### Anything else?

![image](https://github.com/milvus-io/pymilvus/assets/135136620/bfd0dd14-90bf-49cb-a651-5bd6307ba15e)
![bc4aae81-8865-4146-9db3-8a0ceef331af](https://github.com/milvus-io/pymilvus/assets/135136620/e7475694-2ac3-4b63-8827-74fd00036894)

**Comment by XuanYang-cn** [comment]
/assign @qixuan0212 
Please help verify
