### ISSUE TITLE
The following error occurred when I upgraded the version to milvus 2.3.3-gpu and the pymilvus to 2.3.3  :Missing param in entities, a field must have type, name and values

### ISSUE THREAD

**Issue by xiong0827** [milvus-io/pymilvus#1816]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What is your question?

The following error occurred when I upgraded the version to milvus 2.3.3-gpu and the pymilvus to 2.3.3

bin D:\conda\envs\chatglm2\lib\site-packages\bitsandbytes\libbitsandbytes_cuda117.dll
CUDA SETUP: CUDA runtime path found: D:\conda\envs\chatglm2\bin\cudart64_110.dll
CUDA SETUP: Highest compute capability among GPUs detected: 8.6
CUDA SETUP: Detected CUDA version 117
CUDA SETUP: Loading binary D:\conda\envs\chatglm2\lib\site-packages\bitsandbytes\libbitsandbytes_cuda117.dll...
100%|███████████████████████████████████████████████████████████████████████████████| 1003/1003 [00:00<00:00, 996656.46it/s]
1003
ERROR 2023-12-12 15:50:51,245-1d: RPC error: [batch_insert], <ParamError: (code=1, message=Missing param in entities, a field must have type, name and values)>, <Time:{'RPC start': '2023-12-12 15:50:51.245649', 'RPC error': '2023-12-12 15:50:51.245649'}>
Traceback (most recent call last):
  File "E:\360MoveData\Users\Administrator\Desktop\langchain_milvus\core\data_process\load_data.py", line 129, in <module>   
    load_data_db()
  File "E:\360MoveData\Users\Administrator\Desktop\langchain_milvus\core\data_process\load_data.py", line 120, in load_data_db
    insert_milvus(estateCollection,
  File "E:\360MoveData\Users\Administrator\Desktop\langchain_milvus\core\data_process\load_data.py", line 101, in insert_milvus
    res = collection.insert(data=arr, partition_name=partition_name)
  File "D:\conda\envs\chatglm2\lib\site-packages\pymilvus\orm\collection.py", line 497, in insert
    res = conn.batch_insert(
  File "D:\conda\envs\chatglm2\lib\site-packages\pymilvus\decorators.py", line 129, in handler
    raise e from e
  File "D:\conda\envs\chatglm2\lib\site-packages\pymilvus\decorators.py", line 125, in handler
    return func(*args, **kwargs)
  File "D:\conda\envs\chatglm2\lib\site-packages\pymilvus\decorators.py", line 164, in handler
    return func(self, *args, **kwargs)
  File "D:\conda\envs\chatglm2\lib\site-packages\pymilvus\decorators.py", line 104, in handler
    raise e from e
  File "D:\conda\envs\chatglm2\lib\site-packages\pymilvus\decorators.py", line 68, in handler
    return func(*args, **kwargs)
  File "D:\conda\envs\chatglm2\lib\site-packages\pymilvus\client\grpc_handler.py", line 555, in batch_insert
    raise err from err
  File "D:\conda\envs\chatglm2\lib\site-packages\pymilvus\client\grpc_handler.py", line 538, in batch_insert
    request = self._prepare_batch_insert_request(
  File "D:\conda\envs\chatglm2\lib\site-packages\pymilvus\client\grpc_handler.py", line 522, in _prepare_batch_insert_request    else Prepare.batch_insert_param(collection_name, entities, partition_name, fields_info)
  File "D:\conda\envs\chatglm2\lib\site-packages\pymilvus\client\prepare.py", line 517, in batch_insert_param
    location = cls._pre_batch_check(entities, fields_info)
  File "D:\conda\envs\chatglm2\lib\site-packages\pymilvus\client\prepare.py", line 456, in _pre_batch_check
    raise ParamError(
pymilvus.exceptions.ParamError: <ParamError: (code=1, message=Missing param in entities, a field must have type, name and values)>

**Comment by MehediTamim** [comment]
Got same error!!
