### ISSUE TITLE
[Bug]:  [milvus_client] add field to schema is failed with error "'NoneType' object has no attribute 'auto_id'"

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/pymilvus#1864]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

[milvus_client] add field to schema is failed with error "'NoneType' object has no attribute 'auto_id'"

```
schema = milvus_client.create_schema(enable_dynamic_field=True)
>>> schema.add_field("id", DataType.INT64, is_primary=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/orm/schema.py", line 138, in __repr__
    return str(self.to_dict())
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/orm/schema.py", line 230, in to_dict
    "auto_id": self.auto_id,
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/orm/schema.py", line 213, in auto_id
    return self.primary_field.auto_id
AttributeError: 'NoneType' object has no attribute 'auto_id'
```

And 
```
>>> schema = milvus_client.create_schema()
>>>
>>> schema
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/orm/schema.py", line 138, in __repr__
    return str(self.to_dict())
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/orm/schema.py", line 230, in to_dict
    "auto_id": self.auto_id,
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/orm/schema.py", line 213, in auto_id
    return self.primary_field.auto_id
AttributeError: 'NoneType' object has no attribute 'auto_id'
>>> schema.add_field("id", DataType.INT64, is_primary=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/orm/schema.py", line 138, in __repr__
    return str(self.to_dict())
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/orm/schema.py", line 230, in to_dict
    "auto_id": self.auto_id,
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/orm/schema.py", line 213, in auto_id
    return self.primary_field.auto_id
AttributeError: 'NoneType' object has no attribute 'auto_id'
```

### Expected Behavior

No error

### Steps/Code To Reproduce behavior

```python
import time
import numpy as np
from pymilvus import (
    MilvusClient,
    DataType
)

milvus_client = MilvusClient()
schema = milvus_client.create_schema(enable_dynamic_field=True)
schema.add_field("id", DataType.INT64, is_primary=True)
```

### Environment details

```markdown
- Hardware/Softward conditions (OS, CPU, GPU, Memory):
- Method of installation (Docker, or from source):
- Milvus version (v0.3.1, or v0.4.0): master-20240115-fb4fbcf4
- pymilvus version: 2.4.0rc23
- Milvus configuration (Settings you made in `server_config.yaml`):
```

**Comment by binbinlv** [comment]
Verified and fixed:

pymilvus: 2.4.0rc30
milvus: master-20240205-a68b3213

results:
```
>>> schema = milvus_client.create_schema(enable_dynamic_field=True)
>>>
>>> schema.add_field("id", DataType.INT64, is_primary=True)
{'auto_id': False, 'description': '', 'fields': [{'name': 'id', 'description': '', 'type': <DataType.INT64: 5>, 'is_primary': True, 'auto_id': False}], 'enable_dynamic_field': True}
>>>
```
