### ISSUE TITLE
[Bug]:  [milvus_client] The error msg is not user friendly when lack of required parameters for interface create_collection

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/pymilvus#1865]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

 The error msg is not user friendly when lack of required parameters for interface create_collection
```
milvus_client.create_collection(collection_name)
RPC error: [create_collection], <MilvusException: (code=65535, message=strconv.ParseInt: parsing "None": invalid syntax)>, <Time:{'RPC start': '2024-01-16 15:02:20.547216', 'RPC error': '2024-01-16 15:02:20.640490'}>
Failed to create collection: hello_milvus
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 82, in create_collection
    return self._fast_create_collection(
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 139, in _fast_create_collection
    raise ex from ex
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 135, in _fast_create_collection
    conn.create_collection(collection_name, schema, timeout=timeout, **kwargs)
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 135, in handler
    raise e from e
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 131, in handler
    return func(*args, **kwargs)
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 170, in handler
    return func(self, *args, **kwargs)
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 110, in handler
    raise e from e
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 74, in handler
    return func(*args, **kwargs)
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 304, in create_collection
    check_status(status)
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/client/utils.py", line 58, in check_status
    raise MilvusException(status.code, status.reason, status.error_code)
pymilvus.exceptions.MilvusException: <MilvusException: (code=65535, message=strconv.ParseInt: parsing "None": invalid syntax)>
```

### Expected Behavior

The error msg should remind that all the required parameters, like "create_collection() missing 1 required positional argument: 'collection_name'"

### Steps/Code To Reproduce behavior

```python
import time
import numpy as np
from pymilvus import (
    MilvusClient,
    DataType
)

milvus_client = MilvusClient()
collection_name = "hello_milvus"
milvus_client.create_collection(collection_name)
```

### Environment details

```markdown
- Hardware/Softward conditions (OS, CPU, GPU, Memory):
- Method of installation (Docker, or from source):
- Milvus version (v0.3.1, or v0.4.0): master-20240115-fb4fbcf4
- pymilvus version: 2.4.0rc23
- Milvus configuration (Settings you made in `server_config.yaml`):
```

**Comment by binbinlv** [comment]
verified and fixed.
pymilvus: 2.4.0rc30
milvus: master-20240205-a68b3213

results:
```
>>> milvus_client.create_collection(collection_name)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 77, in create_collection
    return self._fast_create_collection(
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 107, in _fast_create_collection
    raise TypeError(msg)
TypeError: missing requried argument: 'dimension'
```
