### ISSUE TITLE
[Bug]: [milvus_client] Search specifying the same metric type with that in create collection reports error "metric type not match: service internal error: UnknownError)"

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/pymilvus#1866]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Search with the same metric type using in create collection report error "metric type not match: service internal error: UnknownError)"

if search without "metric_type", it is successful.

```
>>> search_params = {"metric_type": "L2"}
>>>
>>> result = milvus_client.search(collection_name, vectors_to_search, limit=3, output_fields=["pk", "a", "b"], search_params=search_params)
RPC error: [search], <MilvusException: (code=65535, message=fail to search on QueryNode 1: worker(1) query failed: Assert "metric_str == index_meta.GeMetricType()" at /go/src/github.com/milvus-io/milvus/internal/core/src/segcore/SegmentGrowingImpl.h:291
 => metric type not match: service internal error: UnknownError)>, <Time:{'RPC start': '2024-01-16 18:38:16.881802', 'RPC error': '2024-01-16 18:38:17.696215'}>
Failed to search collection: hello_milvus
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 320, in search
    raise ex from ex
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 306, in search
    res = conn.search(
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 135, in handler
    raise e from e
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 131, in handler
    return func(*args, **kwargs)
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 170, in handler
    return func(self, *args, **kwargs)
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 110, in handler
    raise e from e
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 74, in handler
    return func(*args, **kwargs)
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 786, in search
    return self._execute_search(request, timeout, round_decimal=round_decimal, **kwargs)
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 728, in _execute_search
    raise e from e
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 721, in _execute_search
    check_status(response.status)
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/client/utils.py", line 58, in check_status
    raise MilvusException(status.code, status.reason, status.error_code)
pymilvus.exceptions.MilvusException: <MilvusException: (code=65535, message=fail to search on QueryNode 1: worker(1) query failed: Assert "metric_str == index_meta.GeMetricType()" at /go/src/github.com/milvus-io/milvus/internal/core/src/segcore/SegmentGrowingImpl.h:291
 => metric type not match: service internal error: UnknownError)>
```

### Expected Behavior

do not report error

### Steps/Code To Reproduce behavior

```python
import time
import numpy as np
from pymilvus import (
     MilvusClient,
 )


dim = 8
collection_name = "hello_milvus"
milvus_client = MilvusClient()

milvus_client.create_collection(collection_name, dim, consistency_level="Strong", metric_type="L2")
rng = np.random.default_rng(seed=19530)
rows = [
         {"id": 1, "vector": rng.random((1, dim))[0], "a": 100},
         {"id": 2, "vector": rng.random((1, dim))[0], "b": 200},
         {"id": 3, "vector": rng.random((1, dim))[0], "c": 300},
         {"id": 4, "vector": rng.random((1, dim))[0], "d": 400},
         {"id": 5, "vector": rng.random((1, dim))[0], "e": 500},
         {"id": 6, "vector": rng.random((1, dim))[0], "f": 600},
 ]
insert_result = milvus_client.insert(collection_name, rows, progress_bar=True)
rng = np.random.default_rng(seed=19530)
vectors_to_search = rng.random((1, dim))
result = milvus_client.search(collection_name, vectors_to_search, limit=3, output_fields=["pk", "a", "b"])
search_params = {"metric_type": "L2"}
result = milvus_client.search(collection_name, vectors_to_search, limit=3, output_fields=["pk", "a", "b"], search_params=search_params)
```

### Environment details

```markdown
- Hardware/Softward conditions (OS, CPU, GPU, Memory):
- Method of installation (Docker, or from source):
- Milvus version (v0.3.1, or v0.4.0): master-20240115-fb4fbcf4
- pymilvus version: 2.4.0rc23
- Milvus configuration (Settings you made in `server_config.yaml`):
```

**Comment by binbinlv** [comment]
Verified and fixed.


results:
```
>>> dim = 8
>>> milvus_client.create_collection(collection_name, dim, consistency_level="Strong", metric_type="L2")
>>>
>>> rng = np.random.default_rng(seed=19530)
>>> rows = [
...          {"id": 1, "vector": rng.random((1, dim))[0], "a": 100},
...          {"id": 2, "vector": rng.random((1, dim))[0], "b": 200},
...          {"id": 3, "vector": rng.random((1, dim))[0], "c": 300},
...          {"id": 4, "vector": rng.random((1, dim))[0], "d": 400},
...          {"id": 5, "vector": rng.random((1, dim))[0], "e": 500},
...          {"id": 6, "vector": rng.random((1, dim))[0], "f": 600},
...  ]
>>>
>>> insert_result = milvus_client.insert(collection_name, rows, progress_bar=True)
>>> rng = np.random.default_rng(seed=19530)
>>> vectors_to_search = rng.random((1, dim))
>>> result = milvus_client.search(collection_name, vectors_to_search, limit=3, output_fields=["pk", "a", "b"])

>>>
>>> search_params = {"metric_type": "L2"}
>>>
>>> result = milvus_client.search(collection_name, vectors_to_search, limit=3, output_fields=["pk", "a", "b"], search_params=search_params)

>>>
```
