### ISSUE TITLE
InvalidateCollectionMetaCache failed

### ISSUE THREAD

**Issue by Phobia-Cosmos** [milvus-io/pymilvus#1867]
I am learning from the [Run Milvus using Python](https://milvus.io/docs/example_code.md) using the Milvus lite on my mac directly, and when I first run the code, it encounter the error below and then leave a collection in my DB.However, the second time I run it just few seconds after, everything went right but the collection it made in the first try remains.I don't know why it will the error occurs and I don't know why it returns normal.
```
=== start connecting to Milvus     ===

Does collection hello_milvus exist in Milvus: False

=== Create collection `hello_milvus` ===

RPC error: [create_collection], <MilvusException: (code=65535, message=InvalidateCollectionMetaCache failed, proxyID = 2, err = stack trace: /Users/jibin/Working/milvus-lite/milvus_binary/milvus/pkg/tracer/stack_trace.go:51 github.com/milvus-io/milvus/pkg/tracer.StackTrace
/Users/jibin/Working/milvus-lite/milvus_binary/milvus/internal/util/grpcclient/client.go:515 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).Call
/Users/jibin/Working/milvus-lite/milvus_binary/milvus/internal/util/grpcclient/client.go:529 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).ReCall
/Users/jibin/Working/milvus-lite/milvus_binary/milvus/internal/distributed/proxy/client/client.go:76 github.com/milvus-io/milvus/internal/distributed/proxy/client.wrapGrpcCall[...]
/Users/jibin/Working/milvus-lite/milvus_binary/milvus/internal/distributed/proxy/client/client.go:109 github.com/milvus-io/milvus/internal/distributed/proxy/client.(*Client).InvalidateCollectionMetaCache
/Users/jibin/Working/milvus-lite/milvus_binary/milvus/internal/rootcoord/proxy_client_manager.go:157 github.com/milvus-io/milvus/internal/rootcoord.(*proxyClientManager).InvalidateCollectionMetaCache.func1
/Users/jibin/go/pkg/mod/golang.org/x/sync@v0.1.0/errgroup/errgroup.go:75 golang.org/x/sync/errgroup.(*Group).Go.func1
/opt/homebrew/Cellar/go/1.21.4/libexec/src/runtime/asm_arm64.s:1197 runtime.goexit: attempt #0: rpc error: code = Unknown desc = expectedNodeID=2, actualNodeID=3: node not match: attempt #1: rpc error: code = Unknown desc = expectedNodeID=2, actualNodeID=3: node not match: attempt #2: rpc error: code = Unknown desc = expectedNodeID=2, actualNodeID=3: node not match: attempt #3: rpc error: code = Unknown desc = expectedNodeID=2, actualNodeID=3: node not match: attempt #4: rpc error: code = Unknown desc = expectedNodeID=2, actualNodeID=3: node not match: attempt #5: rpc error: code = Unknown desc = expectedNodeID=2, actualNodeID=3: node not match: attempt #6: rpc error: code = Unknown desc = expectedNodeID=2, actualNodeID=3: node not match: attempt #7: rpc error: code = Unknown desc = expectedNodeID=2, actualNodeID=3: node not match: attempt #8: rpc error: code = Unknown desc = expectedNodeID=2, actualNodeID=3: node not match: attempt #9: rpc error: code = Unknown desc = expectedNodeID=2, actualNodeID=3: node not match)>, <Time:{'RPC start': '2024-01-16 19:27:20.388750', 'RPC error': '2024-01-16 19:28:33.203917'}>
Traceback (most recent call last):
  File "/Users/liuzihao/Desktop/Draft/milvus/hello_Milvus/hello_milvus.py", line 59, in <module>
    hello_milvus = Collection("hello_milvus", schema, consistency_level="Strong")
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/liuzihao/Desktop/Draft/milvus/milvus/lib/python3.11/site-packages/pymilvus/orm/collection.py", line 147, in __init__
    conn.create_collection(self._name, schema, **kwargs)
  File "/Users/liuzihao/Desktop/Draft/milvus/milvus/lib/python3.11/site-packages/pymilvus/decorators.py", line 129, in handler
    raise e from e
  File "/Users/liuzihao/Desktop/Draft/milvus/milvus/lib/python3.11/site-packages/pymilvus/decorators.py", line 125, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/liuzihao/Desktop/Draft/milvus/milvus/lib/python3.11/site-packages/pymilvus/decorators.py", line 164, in handler
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/liuzihao/Desktop/Draft/milvus/milvus/lib/python3.11/site-packages/pymilvus/decorators.py", line 104, in handler
    raise e from e
  File "/Users/liuzihao/Desktop/Draft/milvus/milvus/lib/python3.11/site-packages/pymilvus/decorators.py", line 68, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/liuzihao/Desktop/Draft/milvus/milvus/lib/python3.11/site-packages/pymilvus/client/grpc_handler.py", line 293, in create_collection
    check_status(status)
  File "/Users/liuzihao/Desktop/Draft/milvus/milvus/lib/python3.11/site-packages/pymilvus/client/utils.py", line 54, in check_status
    raise MilvusException(status.code, status.reason, status.error_code)
pymilvus.exceptions.MilvusException: <MilvusException: (code=65535, message=InvalidateCollectionMetaCache failed, proxyID = 2, err = stack trace: /Users/jibin/Working/milvus-lite/milvus_binary/milvus/pkg/tracer/stack_trace.go:51 github.com/milvus-io/milvus/pkg/tracer.StackTrace
/Users/jibin/Working/milvus-lite/milvus_binary/milvus/internal/util/grpcclient/client.go:515 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).Call
/Users/jibin/Working/milvus-lite/milvus_binary/milvus/internal/util/grpcclient/client.go:529 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).ReCall
/Users/jibin/Working/milvus-lite/milvus_binary/milvus/internal/distributed/proxy/client/client.go:76 github.com/milvus-io/milvus/internal/distributed/proxy/client.wrapGrpcCall[...]
/Users/jibin/Working/milvus-lite/milvus_binary/milvus/internal/distributed/proxy/client/client.go:109 github.com/milvus-io/milvus/internal/distributed/proxy/client.(*Client).InvalidateCollectionMetaCache
/Users/jibin/Working/milvus-lite/milvus_binary/milvus/internal/rootcoord/proxy_client_manager.go:157 github.com/milvus-io/milvus/internal/rootcoord.(*proxyClientManager).InvalidateCollectionMetaCache.func1
/Users/jibin/go/pkg/mod/golang.org/x/sync@v0.1.0/errgroup/errgroup.go:75 golang.org/x/sync/errgroup.(*Group).Go.func1
/opt/homebrew/Cellar/go/1.21.4/libexec/src/runtime/asm_arm64.s:1197 runtime.goexit: attempt #0: rpc error: code = Unknown desc = expectedNodeID=2, actualNodeID=3: node not match: attempt #1: rpc error: code = Unknown desc = expectedNodeID=2, actualNodeID=3: node not match: attempt #2: rpc error: code = Unknown desc = expectedNodeID=2, actualNodeID=3: node not match: attempt #3: rpc error: code = Unknown desc = expectedNodeID=2, actualNodeID=3: node not match: attempt #4: rpc error: code = Unknown desc = expectedNodeID=2, actualNodeID=3: node not match: attempt #5: rpc error: code = Unknown desc = expectedNodeID=2, actualNodeID=3: node not match: attempt #6: rpc error: code = Unknown desc = expectedNodeID=2, actualNodeID=3: node not match: attempt #7: rpc error: code = Unknown desc = expectedNodeID=2, actualNodeID=3: node not match: attempt #8: rpc error: code = Unknown desc = expectedNodeID=2, actualNodeID=3: node not match: attempt #9: rpc error: code = Unknown desc = expectedNodeID=2, actualNodeID=3: node not match)>
```

_Originally posted by @Phobia-Cosmos in https://github.com/milvus-io/milvus/issues/21181#issuecomment-1893580762_

**Comment by Phobia-Cosmos** [comment]
Oh the database seems to be the embedded one, am i right?

**Comment by XuanYang-cn** [comment]
seems fixes
