### ISSUE TITLE
[Bug]: [milvus_client] The error msg does not show the complete usage for delete without all the required parameters

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/pymilvus#1870]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The error msg does not show the complete usage for delete without all the required parameters:
when run
```
milvus_client.delete(collection_name)
```
it shows "code=1, message=expr cannot be empty", but actually either ids and expr are OK, here only shows expr.

And "expr" could be replaced with the parameter name "filter".

### Expected Behavior

sth like "ids or expr cannot be empty"

and it is better to replace "expr"  with the parameter name "filter"

### Steps/Code To Reproduce behavior

```python
import time
import numpy as np
from pymilvus import (
    MilvusClient,
)

fmt = "\n=== {:30} ===\n"
dim = 8
collection_name = "hello_milvus"
milvus_client = MilvusClient()

has_collection = milvus_client.has_collection(collection_name, timeout=5)
if has_collection:
    milvus_client.drop_collection(collection_name)
milvus_client.create_collection(collection_name, dim, consistency_level="Strong", metric_type="L2")

print(fmt.format("    all collections    "))
print(milvus_client.list_collections())

print(fmt.format(f"schema of collection {collection_name}"))
print(milvus_client.describe_collection(collection_name))

rng = np.random.default_rng(seed=19530)
rows = [
        {"id": 1, "vector": rng.random((1, dim))[0], "a": 100},
        {"id": 2, "vector": rng.random((1, dim))[0], "b": 200},
        {"id": 3, "vector": rng.random((1, dim))[0], "c": 300},
        {"id": 4, "vector": rng.random((1, dim))[0], "d": 400},
        {"id": 5, "vector": rng.random((1, dim))[0], "e": 500},
        {"id": 6, "vector": rng.random((1, dim))[0], "f": 600},
]

print(fmt.format("Start inserting entities"))
insert_result = milvus_client.insert(collection_name, rows, progress_bar=True)
print(fmt.format("Inserting entities done"))
print(insert_result)
milvus_client.delete(collection_name)
```

### Environment details

```markdown
- Hardware/Softward conditions (OS, CPU, GPU, Memory):
- Method of installation (Docker, or from source):
- Milvus version (v0.3.1, or v0.4.0): master-20240115-fb4fbcf4
- pymilvus version: 2.4.0rc23
- Milvus configuration (Settings you made in `server_config.yaml`):
```

**Comment by binbinlv** [comment]
Verified and fixed.
pymilvus: 2.4.0rc30
milvus: master-20240205-a68b3213

result:
```
>>> milvus_client.delete(collection_name)
RPC error: [delete], <ParamError: (code=1, message=filter or ids cannot be empty)>, <Time:{'RPC start': '2024-02-05 15:15:30.704760', 'RPC error': '2024-02-05 15:15:30.704865'}>
Failed to delete primary keys in collection: hello_milvus
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 558, in delete
    raise ex from ex
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 546, in delete
    res = conn.delete(
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 135, in handler
    raise e from e
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 131, in handler
    return func(*args, **kwargs)
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 170, in handler
    return func(self, *args, **kwargs)
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 110, in handler
    raise e from e
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 74, in handler
    return func(*args, **kwargs)
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 606, in delete
    raise err from err
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 584, in delete
    req = Prepare.delete_request(
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/client/prepare.py", line 565, in delete_request
    check_str(expr, param_name)
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/client/prepare.py", line 559, in check_str
    raise ParamError(message=f"{prefix} cannot be empty")
pymilvus.exceptions.ParamError: <ParamError: (code=1, message=filter or ids cannot be empty)>
```
