### ISSUE TITLE
[Bug]: [milvus_client][not fix] The name is not consistent between "NotLoad" and "Loaded" for the return of interface "get_load_state" 

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/pymilvus#1871]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The interface "get_load_state" reports unexpected error when input the right parameter

```
milvus_client.get_load_state("high_level_api_RVJQjyAY")
Unexpected error: [get_load_state], get_load_state() got an unexpected keyword argument 'tiemout', <Time: {'RPC start': '2024-01-17 16:02:42.570920', 'Exception': '2024-01-17 16:02:42.571020'}>
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 706, in get_load_state
    raise ex from ex
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 704, in get_load_state
    state = conn.get_load_state(collection_name, partition_names, tiemout=timeout, **kwargs)
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 153, in handler
    raise MilvusException(message=f"Unexpected error, message=<{e!s}>") from e
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=Unexpected error, message=<get_load_state() got an unexpected keyword argument 'tiemout'>)>
```

### Expected Behavior

Return loading state with no errors

### Steps/Code To Reproduce behavior

```python
import time
import numpy as np
from pymilvus import (
    MilvusClient,
)

dim = 8
collection_name = "hello_milvus"
milvus_client = MilvusClient()

has_collection = milvus_client.has_collection(collection_name, timeout=5)
if has_collection:
    milvus_client.drop_collection(collection_name)
milvus_client.create_collection(collection_name, dim)
milvus_client.get_load_state(collection_name)
```

### Environment details

```markdown
- Hardware/Softward conditions (OS, CPU, GPU, Memory):
- Method of installation (Docker, or from source):
- Milvus version (v0.3.1, or v0.4.0): master-20240115-fb4fbcf4
- pymilvus version: 2.4.0rc23
- Milvus configuration (Settings you made in `server_config.yaml`):
```

**Comment by binbinlv** [comment]
Verified and fixed:
pymilvus: 2.4.0rc30
milvus: master-20240205-a68b3213

```
>>> milvus_client.create_collection(collection_name, dim)
>>>
>>> milvus_client.get_load_state(collection_name)
{'state': <LoadState: Loaded>}
>>>
>>>
>>> milvus_client.release_collection(collection_name)
>>> milvus_client.get_load_state(collection_name)
{'state': <LoadState: NotLoad>}
>>>
```

**Comment by binbinlv** [comment]
The status name "Loaded" and "NotLoad", maybe "NotLoaded" is more consistent with "Loaded"?

**Comment by czs007** [comment]
Its definition is from the following enum.
enum LoadState {
    LoadStateNotExist = 0;
    LoadStateNotLoad = 1;
    LoadStateLoading = 2;
    LoadStateLoaded = 3;
}
