### ISSUE TITLE
[Bug]: [milvus_client] create collection with invalid metric_type does not report error

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/pymilvus#1872]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

create collection with invalid metric_type does not report error

No errors
```
>>> milvus_client.create_collection(collection_name, dim, metric_type="invalid")
>>>
>>>
```

### Expected Behavior

Report errors

### Steps/Code To Reproduce behavior

```python
import time
import numpy as np
from pymilvus import (
    MilvusClient,
)

dim = 8
collection_name = "hello_milvus"
milvus_client = MilvusClient("")
milvus_client.create_collection(collection_name, dim, consistency_level="Strong", metric_type="invalid")
```

### Environment details

```markdown
- Hardware/Softward conditions (OS, CPU, GPU, Memory):
- Method of installation (Docker, or from source):
- Milvus version (v0.3.1, or v0.4.0): master-20240115-fb4fbcf4
- pymilvus version: 2.4.0rc23
- Milvus configuration (Settings you made in `server_config.yaml`):
```

**Comment by binbinlv** [comment]
Verified and fixed:

pymilvus: 2.4.0rc30
milvus: master-20240205-a68b3213

results:
```
>>> milvus_client.create_collection(collection_name, dim, consistency_level="Strong", metric_type="invalid")
RPC error: [create_index], <MilvusException: (code=65535, message=metric type invalid not found or not supported, supported: [L2 IP COSINE HAMMING JACCARD])>, <Time:{'RPC start': '2024-02-05 15:25:49.607844', 'RPC error': '2024-02-05 15:25:49.740955'}>
Failed to create an index on collection: hello_milvus
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 77, in create_collection
    return self._fast_create_collection(
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 146, in _fast_create_collection
    self.create_index(collection_name, index_params, timeout=timeout)
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 158, in create_index
    self._create_index(collection_name, index_param, timeout=timeout, **kwargs)
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 188, in _create_index
    raise ex from ex
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 177, in _create_index
    conn.create_index(
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 135, in handler
    raise e from e
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 131, in handler
    return func(*args, **kwargs)
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 170, in handler
    return func(self, *args, **kwargs)
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 110, in handler
    raise e from e
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 74, in handler
    return func(*args, **kwargs)
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 936, in create_index
    check_status(status)
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/client/utils.py", line 60, in check_status
    raise MilvusException(status.code, status.reason, status.error_code)
pymilvus.exceptions.MilvusException: <MilvusException: (code=65535, message=metric type invalid not found or not supported, supported: [L2 IP COSINE HAMMING JACCARD])>
```
