### ISSUE TITLE
[Bug]: [milvus_client] The error message is not meaningful when input wrong type value to parameter "partition_name" for interface "get_partition_stats"

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/pymilvus#1879]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The error message is not meaningful when input wrong type value to parameter "partition_name"

error: Unexpected error, message=<bad argument type for built-in operation>

```
>>> milvus_client.get_partition_stats(collection_name, ['_default', 'default_1'])
Unexpected error: [get_partition_stats], bad argument type for built-in operation, <Time: {'RPC start': '2024-01-19 16:32:17.006335', 'Exception': '2024-01-19 16:32:17.006428'}>
Traceback (most recent call last):
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 131, in handler
    return func(*args, **kwargs)
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 170, in handler
    return func(self, *args, **kwargs)
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 112, in handler
    raise e from e
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 74, in handler
    return func(*args, **kwargs)
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 455, in get_partition_stats
    req = Prepare.get_partition_stats_request(collection_name, partition_name)
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/client/prepare.py", line 854, in get_partition_stats_request
    return milvus_types.GetPartitionStatisticsRequest(
TypeError: bad argument type for built-in operation

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 830, in get_partition_stats
    return conn.get_partition_stats(collection_name, partition_name, timeout=timeout, **kwargs)
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 153, in handler
    raise MilvusException(message=f"Unexpected error, message=<{e!s}>") from e
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=Unexpected error, message=<bad argument type for built-in operation>)>
```

### Expected Behavior

Report type not right error

### Steps/Code To Reproduce behavior

```python
import time
import numpy as np
from pymilvus import (
    MilvusClient,
)

dim = 8
collection_name = "hello_milvus"
milvus_client = MilvusClient()
milvus_client.create_collection(collection_name, dim)
milvus_client.get_partition_stats(collection_name, ['_default', 'default_1'])
```

### Environment details

```markdown
- Hardware/Softward conditions (OS, CPU, GPU, Memory):
- Method of installation (Docker, or from source):
- Milvus version (v0.3.1, or v0.4.0): master-20240115-fb4fbcf4
- pymilvus version: 2.4.0rc23
- Milvus configuration (Settings you made in `server_config.yaml`):
```

**Comment by binbinlv** [comment]
Verified and fixed:
pymilvus: 2.4.0rc30
milvus: master-20240205-a68b3213

results:
```
>>> milvus_client.get_partition_stats(collection_name, ['_default', 'default_1'])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 880, in get_partition_stats
    raise TypeError(msg)
TypeError: wrong type of argument 'partition_name', str expected, got 'list'
```
