### ISSUE TITLE
[Bug]: [milvus_client] The error is not proper when there is no parameter for list_aliases() 

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/pymilvus#1891]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

 The result of list_aliases() is not a list (NoneType)
```
>>> aliases = milvus_client.list_aliases()
>>> aliases
>>> type(aliases)
<class 'NoneType'>
```

### Expected Behavior

Return all aliases list

### Steps/Code To Reproduce behavior

```python
import time
import numpy as np
from pymilvus import (
    MilvusClient,
 )
dim = 8
collection_name = "hello_milvus_no"
milvus_client = MilvusClient()
milvus_client.create_collection(collection_name, dim)
alias = "alias"
milvus_client.create_alias(collection_name, alias)
milvus_client.list_aliases()
aliases = milvus_client.list_aliases()
```

### Environment details

```markdown
- Hardware/Softward conditions (OS, CPU, GPU, Memory):
- Method of installation (Docker, or from source):
- Milvus version (v0.3.1, or v0.4.0): master-20240122-a77693aa
- pymilvus version: 2.4.0rc26
- Milvus configuration (Settings you made in `server_config.yaml`):
```

**Comment by czs007** [comment]
see also https://github.com/milvus-io/milvus/pull/30533

**Comment by binbinlv** [comment]
Verified, now list_aliases works now:

```
>>> milvus_client.list_aliases(collection_name)
{'aliases': ['alias'], 'db_name': 'default'}
```

But when there is no parameter, the message is not proper:

```
>>> milvus_client.list_aliases()
RPC error: [list_aliases], <ParamError: (code=1, message=`collection_name` value  is illegal)>, <Time:{'RPC start': '2024-02-06 10:18:10.106884', 'RPC error': '2024-02-06 10:18:10.106974'}>
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 964, in list_aliases
    return conn.list_aliases(collection_name, timeout=timeout, **kwargs)
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 135, in handler
    raise e from e
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 131, in handler
    return func(*args, **kwargs)
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 170, in handler
    return func(self, *args, **kwargs)
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 110, in handler
    raise e from e
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 74, in handler
    return func(*args, **kwargs)
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 901, in list_aliases
    check_pass_param(collection_name=collection_name, timeout=timeout)
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/client/check.py", line 356, in check_pass_param
    checker.check(key, value)
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/client/check.py", line 342, in check
    _raise_param_error(key, value)
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/client/check.py", line 234, in _raise_param_error
    raise ParamError(message=f"`{param_name}` value {param_value} is illegal")
pymilvus.exceptions.ParamError: <ParamError: (code=1, message=`collection_name` value  is illegal)>
```

**Comment by binbinlv** [comment]
Verified and fixed:
pymilvus: 2.4.0rc34
milvus: master-20240205-a68b3213

```
>>> milvus_client.create_alias(collection_name, alias)
>>> milvus_client.list_aliases()
{'aliases': ['alias', 'collection_alias_mMvQJu8p'], 'db_name': 'default'}
>>> aliases = milvus_client.list_aliases()
>>>
>>>
>>> aliases
{'aliases': ['collection_alias_mMvQJu8p', 'alias'], 'db_name': 'default'}
```
