### ISSUE TITLE
[Bug]: [milvus_client] The error message could be better when insert invalid data 

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/pymilvus#1894]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The error message could be better when insert invalid data  by providing what is the "valid rows":

```
[2024-01-25 14:34:52 - ERROR - ci_test]: (api_response) : <ParamError: (code=1, message=None rows, please provide valid row data.)> (api_request.py:46)
```

### Expected Behavior

Report more specific and operation-able error message by explaining what is the valid row data

### Steps/Code To Reproduce behavior

```python
import time
import numpy as np
from pymilvus import (
    MilvusClient,
 )
dim = 8
collection_name = "hello_milvus_no"
milvus_client = MilvusClient()
milvus_client.create_collection(collection_name, dim)
milvus_client.insert(collection_name, "data")
```

### Environment details

```markdown
- Hardware/Softward conditions (OS, CPU, GPU, Memory):
- Method of installation (Docker, or from source):
- Milvus version (v0.3.1, or v0.4.0): master-20240122-a77693aa
- pymilvus version: 2.4.0rc26
- Milvus configuration (Settings you made in `server_config.yaml`):
```

**Comment by binbinlv** [comment]
Verified and fixed:
pymilvus: 2.4.0rc30
milvus: master-20240205-a68b3213

```
>>> milvus_client.insert(collection_name, "data")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 225, in insert
    raise TypeError(msg)
TypeError: wrong type of argument 'data',expected 'Dict' or list of 'Dict', got 'str'
```
