### ISSUE TITLE
[Bug]: [milvus_client]  Insert invalid empty data  successfully without any errors

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/pymilvus#1895]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Insert invalid empty data  successfully without any errors

```
milvus_client.insert(collection_name, "")
{'insert_count': 0}
```

### Expected Behavior

Report data not valid error

### Steps/Code To Reproduce behavior

```python
import time
import numpy as np
from pymilvus import (
    MilvusClient,
 )
dim = 8
collection_name = "hello_milvus_no"
milvus_client = MilvusClient()
milvus_client.create_collection(collection_name, dim)
milvus_client.insert(collection_name, "")
```

### Environment details

```markdown
- Hardware/Softward conditions (OS, CPU, GPU, Memory):
- Method of installation (Docker, or from source):
- Milvus version (v0.3.1, or v0.4.0): master-20240122-a77693aa
- pymilvus version: 2.4.0rc26
- Milvus configuration (Settings you made in `server_config.yaml`):
```

**Comment by binbinlv** [comment]
And same issue to upsert()
```
milvus_client.upsert(collection_name, "")
{'upsert_count': 0}
```

**Comment by binbinlv** [comment]
Verified and fixed:
pymilvus: 2.4.0rc30
milvus: master-20240205-a68b3213

results:
```
>>> milvus_client.insert(collection_name, "")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 225, in insert
    raise TypeError(msg)
TypeError: wrong type of argument 'data',expected 'Dict' or list of 'Dict', got 'str'
```
