### ISSUE TITLE
[Bug]: [milvus_client]  The error message is not valid when input invalid type data to "partition_names" of interface "release_partitions"

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/pymilvus#1896]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

 The error message is not valid when input invalid type data to "partition_names" of interface "release_partitions"

```
code=200, message=partition not found[partition=12-s])
```

### Expected Behavior

In other interfaces, like create_partition, drop_partition, it reports:
```
Invalid partition name: {partition_name}. The first character of a partition name must be an underscore or letter.]
```

### Steps/Code To Reproduce behavior

```python
import time
import numpy as np
from pymilvus import (
    MilvusClient,
)

milvus_client = MilvusClient()
collection_name = "hello_milvus"
milvus_client.release_partitions(collection_name, "") 
milvus_client.release_partitions(collection_name, "%$#")
milvus_client.release_partitions(collection_name,  ["%$#"])
```

### Environment details

```markdown
- Hardware/Softward conditions (OS, CPU, GPU, Memory):
- Method of installation (Docker, or from source):
- Milvus version (v0.3.1, or v0.4.0):master-20240122-a77693aa
- Pymilvus version: 2.4.0rc26
- Milvus configuration (Settings you made in `server_config.yaml`):
```

**Comment by binbinlv** [comment]
Verified and fixed:


results:
```
>>> milvus_client.release_partitions(collection_name, "")
RPC error: [release_partitions], <MilvusException: (code=200, message=partition not found[partition=])>, <Time:{'RPC start': '2024-02-05 15:56:45.397690', 'RPC error': '2024-02-05 15:56:45.479787'}>
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 871, in release_partitions
    conn.release_partitions(collection_name, partition_names, timeout=timeout, **kwargs)
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 135, in handler
    raise e from e
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 131, in handler
    return func(*args, **kwargs)
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 170, in handler
    return func(self, *args, **kwargs)
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 110, in handler
    raise e from e
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 74, in handler
    return func(*args, **kwargs)
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 1275, in release_partitions
    check_status(response)
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/client/utils.py", line 60, in check_status
    raise MilvusException(status.code, status.reason, status.error_code)
pymilvus.exceptions.MilvusException: <MilvusException: (code=200, message=partition not found[partition=])>
```

```
pymilvus.exceptions.MilvusException: <MilvusException: (code=200, message=partition not found[partition=%$#])>
```
