### ISSUE TITLE
[Bug]: [milvus_client] The state is not proper when get the load state of the non-exist partition

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/pymilvus#1925]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The load status is not right when get the load state of the non-exist partition

current, if other partition is loaded, then the non-exist partition is loaded;
if other patition is NotLoad, then the non-exist partition is NotLoad.

But when the collection is not existed, the load state is "NotExist"

### Expected Behavior

when collection_name is not exists, it return:
{'state': <LoadState: NotExist>}

I think it should keep the consistency of these two behaviors.

### Steps/Code To Reproduce behavior

```python
import time
import numpy as np
from pymilvus import (
    MilvusClient,
)

dim = 8
collection_name = "hello_milvus"
milvus_client = MilvusClient()
milvus_client.create_collection(collection_name, dim, consistency_level="Strong", metric_type="L2")
milvus_client.get_load_state(collection_name, partition_name="non-existed")
milvus_client.release_collection(collection_name)
milvus_client.get_load_state(collection_name, partition_name="non-existed")
```

### Environment details

```markdown
- Hardware/Softward conditions (OS, CPU, GPU, Memory):
- Method of installation (Docker, or from source):
- Milvus version (v0.3.1, or v0.4.0):master-20240205-a68b3213
- Pymilvus version: 2.4.0rc34
- Milvus configuration (Settings you made in `server_config.yaml`):
```

**Comment by binbinlv** [comment]
The result:
```
>>> client.get_load_state("binbin_schema_1", partition_name="non-existed")
RPC error: [get_load_state], <MilvusException: (code=200, message=partition not found[partition=non-existed])>, <Time:{'RPC start': '2024-03-04 16:42:50.783485', 'RPC error': '2024-03-04 16:43:33.293897'}>
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 721, in get_load_state
    raise ex from ex
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/milvus_client/milvus_client.py", line 719, in get_load_state
    state = conn.get_load_state(collection_name, partition_names, timeout=timeout, **kwargs)
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 135, in handler
    raise e from e
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 131, in handler
    return func(*args, **kwargs)
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 170, in handler
    return func(self, *args, **kwargs)
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 110, in handler
    raise e from e
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/decorators.py", line 74, in handler
    return func(*args, **kwargs)
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 1295, in get_load_state
    check_status(response.status)
  File "/Users/binbin/milvus_latest/lib/python3.8/site-packages/pymilvus/client/utils.py", line 60, in check_status
    raise MilvusException(status.code, status.reason, status.error_code)
pymilvus.exceptions.MilvusException: <MilvusException: (code=200, message=partition not found[partition=non-existed])>
```
