### ISSUE TITLE
[Bug]: [mmap] Enable mmap for index through alter_index and report an error

### ISSUE THREAD

**Issue by elstic** [milvus-io/pymilvus#1931]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

when I set mmap to index 
```
hello_milvus.alter_index("default_index_name", {'mmap.enabled': True})
```

pymilvus error:
```
Unexpected error: [alter_index], status, <Time: {'RPC start': '2024-02-22 10:37:55.533745', 'Exception': '2024-02-22 10:37:55.536358'}>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 131, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 170, in handler
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 112, in handler
    raise e from e
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 74, in handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 942, in alter_index
    status = response.status
AttributeError: status

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "sss.py", line 107, in <module>
    hello_milvus.alter_index("default_index_name", {'mmap.enabled': True})
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 1392, in alter_index
    return conn.alter_index(self._name, index_name, extra_params, timeout=timeout)
  File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 153, in handler
    raise MilvusException(message=f"Unexpected error, message=<{e!s}>") from e
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=Unexpected error, message=<status>)>

```

### Steps/Code To Reproduce behavior

```markdown
1. connect to Milvus
  2. create collection
  3. insert data
  4. create index
  5. set index enable mmap => fail 
  5. search, query
```

### Environment details

```markdown
- Hardware/Softward conditions (OS, CPU, GPU, Memory):
- Method of installation (Docker, or from source):
- Milvus version (v0.3.1, or v0.4.0):master-20240222-e5353ad0 
- pymilvus==2.4.0rc11
```

**Comment by sunby** [comment]
fixed in https://github.com/milvus-io/pymilvus/pull/1932

**Comment by elstic** [comment]
#### New issue exists, alter_index sets non-existing index_name no error reported

Part of the code
```
hello_milvus.create_index("float_vector", index, index_name="default_index_name")

hello_milvus.alter_index("rand_s", {'mmap.enabled': True})
```

**Comment by elstic** [comment]
> #### New issue exists, alter_index sets non-existing index_name no error reported
> Part of the code
> 
> ```
> hello_milvus.create_index("float_vector", index, index_name="default_index_name")
> 
> hello_milvus.alter_index("rand_s", {'mmap.enabled': True})
> ```

issue fixed
Verify image: master-20240301-63874036-amd64
