### ISSUE TITLE
[QUESTION]: what milvus version need while use hybrid_search for bge-m3

### ISSUE THREAD

**Issue by wayne2tech** [milvus-io/pymilvus#2000]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What is your question?

when i use hybrid search code, i got the error below:
Traceback (most recent call last):
  File "/data/guoweizhang/code/llm-knowledge-base/tests/test_bge_m3.py", line 88, in <module>
    col.create_index("sparse_vector", sparse_index)
  File "/root/.conda/envs/llm_know/lib/python3.10/site-packages/pymilvus/orm/collection.py", line 1364, in create_index
    return conn.create_index(self._name, field_name, index_params, timeout=timeout, **kwargs)
  File "/root/.conda/envs/llm_know/lib/python3.10/site-packages/pymilvus/decorators.py", line 147, in handler
    raise e from e
  File "/root/.conda/envs/llm_know/lib/python3.10/site-packages/pymilvus/decorators.py", line 143, in handler
    return func(*args, **kwargs)
  File "/root/.conda/envs/llm_know/lib/python3.10/site-packages/pymilvus/decorators.py", line 182, in handler
    return func(self, *args, **kwargs)
  File "/root/.conda/envs/llm_know/lib/python3.10/site-packages/pymilvus/decorators.py", line 122, in handler
    raise e from e
  File "/root/.conda/envs/llm_know/lib/python3.10/site-packages/pymilvus/decorators.py", line 87, in handler
    return func(*args, **kwargs)
  File "/root/.conda/envs/llm_know/lib/python3.10/site-packages/pymilvus/client/grpc_handler.py", line 980, in create_index
    check_status(status)
  File "/root/.conda/envs/llm_know/lib/python3.10/site-packages/pymilvus/client/utils.py", line 60, in check_status
    raise MilvusException(status.code, status.reason, status.error_code)
pymilvus.exceptions.MilvusException: <MilvusException: (code=1100, message=create index on json field is not supported: expected=supported field, actual=create index on 104 field: invalid parameter)>

pymilvus package version: 2.4.0
docker version: 2.3.x

**Comment by czs007** [comment]
@wayne2tech hello
you need upgrade your milvus to version 2.4.0-rc.1(https://github.com/milvus-io/milvus/releases/tag/v2.4.0-rc.1) to use sparse vector.
However, upon reviewing your code, it appears that you are attempting to index data of the JSON type. Currently, we do not support indexing JSON data（Milvus 3.0 will support indexing JSON data.）.
