### ISSUE TITLE
[Bug]: [create_partition], <_MultiThreadedRendezvous: StatusCode.UNIMPLEMENTED,

### ISSUE THREAD

**Issue by gallupliu** [milvus-io/pymilvus#2091]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

`grpc RpcError: [create_partition], <_MultiThreadedRendezvous: StatusCode.UNIMPLEMENTED, >, <Time:{'RPC start': '2024-05-15 14:47:17.303055', 'gRPC error': '2024-05-15 14:47:17.304527'}>
Traceback (most recent call last):
  File "/Users/chenxuan/work/recall_services/milvus_start.py", line 27, in <module>
    client.create_partition(
  File "/Users/chenxuan/miniconda3/envs/dev/lib/python3.11/site-packages/pymilvus/milvus_client/milvus_client.py", line 764, in create_partition
    conn.create_partition(collection_name, partition_name, timeout=timeout, **kwargs)
  File "/Users/chenxuan/miniconda3/envs/dev/lib/python3.11/site-packages/pymilvus/decorators.py", line 161, in handler
    raise e from e
  File "/Users/chenxuan/miniconda3/envs/dev/lib/python3.11/site-packages/pymilvus/decorators.py", line 143, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chenxuan/miniconda3/envs/dev/lib/python3.11/site-packages/pymilvus/decorators.py", line 182, in handler
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chenxuan/miniconda3/envs/dev/lib/python3.11/site-packages/pymilvus/decorators.py", line 91, in handler
    raise e from e
  File "/Users/chenxuan/miniconda3/envs/dev/lib/python3.11/site-packages/pymilvus/decorators.py", line 87, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chenxuan/miniconda3/envs/dev/lib/python3.11/site-packages/pymilvus/client/grpc_handler.py", line 401, in create_partition
    response = rf.result()
               ^^^^^^^^^^^
  File "/Users/chenxuan/miniconda3/envs/dev/lib/python3.11/site-packages/grpc/_channel.py", line 880, in result
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNIMPLEMENTED
	details = ""
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2024-05-15T14:47:17.304359+08:00", grpc_status:12, grpc_message:""}"
>`

### Steps/Code To Reproduce behavior

```markdown
from pymilvus import MilvusClient

# 1. Set up a Milvus client
client = MilvusClient(
    uri="./demo.db"
)

# 2. Create a collection
client.create_collection(
    collection_name="quick_setup",
    dimension=5,
    metric_type="IP"
)
data=[
    {"id": 10, "vector": [-0.5570353903748935, -0.8997887893201304, -0.7123782431855732, -0.6298990746450119, 0.6699215060604258], "color": "red_1202"},
    {"id": 11, "vector": [0.6319019033373907, 0.6821488267878275, 0.8552303045704168, 0.36929791364943054, -0.14152860714878068], "color": "blue_4150"},
    {"id": 12, "vector": [0.9483947484855766, -0.32294203351925344, 0.9759290319978025, 0.8262982148666174, -0.8351194181285713], "color": "orange_4590"},
    {"id": 13, "vector": [-0.5449109892498731, 0.043511240563786524, -0.25105249484790804, -0.012030655265886425, -0.0010987671273892108], "color": "pink_9619"},
    {"id": 14, "vector": [0.6603339372951424, -0.10866551787442225, -0.9435597754324891, 0.8230244263466688, -0.7986720938400362], "color": "orange_4863"},
    {"id": 15, "vector": [-0.8825129181091456, -0.9204557711667729, -0.935350065513425, 0.5484069690287079, 0.24448151140671204], "color": "orange_7984"},
    {"id": 16, "vector": [0.6285586391568163, 0.5389064528263487, -0.3163366239905099, 0.22036279378888013, 0.15077052220816167], "color": "blue_9010"},
    {"id": 17, "vector": [-0.20151825016059233, -0.905239387635804, 0.6749305353372479, -0.7324272081377843, -0.33007998971889263], "color": "blue_4521"},
    {"id": 18, "vector": [0.2432286610792349, 0.01785636564206139, -0.651356982731391, -0.35848148851027895, -0.7387383128324057], "color": "orange_2529"},
    {"id": 19, "vector": [0.055512329053363674, 0.7100266349039421, 0.4956956543575197, 0.24541352586717702, 0.4209030729923515], "color": "red_9437"}
]

client.create_partition(
    collection_name="quick_setup",
    partition_name="partitionA"
)

res = client.insert(
    collection_name="quick_setup",
    data=data,
    partition_name="partitionA"
)

print(res)
```

### Environment details

```markdown
pymilvus 2.42
os:mac
```

### Anything else?

none

**Comment by XuanYang-cn** [comment]
@gallupliu MilvusLite Doesn't support partition related operations now. Please refer to 
https://github.com/milvus-io/milvus-lite.git for supported feature and roadmaps.

**Comment by armangrigoryan96** [comment]
but it used to support, no?
