### ISSUE TITLE
[Bug]: <MilvusException: (code=1, message=Unexpected error, message=<Cannot invoke RPC: Channel closed!>)>

### ISSUE THREAD

**Issue by ligjn** [milvus-io/pymilvus#2103]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

  File "/root/miniconda3/lib/python3.9/site-packages/pymilvus/decorators.py", line 131, in handler
    return func(*args, **kwargs)
  File "/root/miniconda3/lib/python3.9/site-packages/pymilvus/decorators.py", line 170, in handler
    return func(self, *args, **kwargs)
  File "/root/miniconda3/lib/python3.9/site-packages/pymilvus/decorators.py", line 112, in handler
    raise e from e
  File "/root/miniconda3/lib/python3.9/site-packages/pymilvus/decorators.py", line 74, in handler
    return func(*args, **kwargs)
  File "/root/miniconda3/lib/python3.9/site-packages/pymilvus/client/grpc_handler.py", line 353, in describe_collection
    response = rf.result()
  File "/root/miniconda3/lib/python3.9/site-packages/grpc/_interceptor.py", line 171, in result
    raise self._exception
  File "/root/miniconda3/lib/python3.9/site-packages/grpc/_interceptor.py", line 389, in future
    return self._interceptor.intercept_unary_unary(
  File "/root/miniconda3/lib/python3.9/site-packages/pymilvus/client/interceptor.py", line 35, in intercept_unary_unary
    response = continuation(new_details, next(new_request_iterator))
  File "/root/miniconda3/lib/python3.9/site-packages/grpc/_interceptor.py", line 379, in continuation
    return self._thunk(new_method).future(
  File "/root/miniconda3/lib/python3.9/site-packages/grpc/_channel.py", line 1197, in future
    call = self._managed_call(
  File "/root/miniconda3/lib/python3.9/site-packages/grpc/_channel.py", line 1709, in create
    call = state.channel.integrated_call(
  File "src/python/grpcio/grpc/_cython/_cygrpc/channel.pyx.pxi", line 502, in grpc._cython.cygrpc.Channel.integrated_call
  File "src/python/grpcio/grpc/_cython/_cygrpc/channel.pyx.pxi", line 318, in grpc._cython.cygrpc._integrated_call
  File "src/python/grpcio/grpc/_cython/_cygrpc/channel.pyx.pxi", line 236, in grpc._cython.cygrpc._call
  File "src/python/grpcio/grpc/_cython/_cygrpc/channel.pyx.pxi", line 281, in grpc._cython.cygrpc._call
ValueError: Cannot invoke RPC: Channel closed!

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/education-ai/ai-backend/common/chunk_embedding.py", line 136, in get_content_by_kw
    collection = Collection(collection_name)
  File "/root/miniconda3/lib/python3.9/site-packages/pymilvus/orm/collection.py", line 117, in __init__
    resp = conn.describe_collection(self._name, **kwargs)
  File "/root/miniconda3/lib/python3.9/site-packages/pymilvus/decorators.py", line 153, in handler
    raise MilvusException(message=f"Unexpected error, message=<{e!s}>") from e
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=Unexpected error, message=<Cannot invoke RPC: Channel closed!>)>

The above is my error message. This problem occasionally occurs, but it greatly affects the business experience. May I ask what is the reason for this problem? What should I do to fix it.

### Environment details

```markdown
- Hardware/Softward conditions (OS, CPU, GPU, Memory): centos 7.9, cpu 64core, 128GMemroy
- Method of installation (Docker, or from source): Docker
- Milvus version (v0.3.1, or v0.4.0):  v2.4.0
- Milvus configuration (Settings you made in `server_config.yaml`):
version: '3.5'

services:
  etcd:
    container_name: milvus-etcd
    image: quay.io/coreos/etcd:v3.5.5
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/etcd:/etcd
    command: etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd
    healthcheck:
      test: ["CMD", "etcdctl", "endpoint", "health"]
      interval: 30s
      timeout: 20s
      retries: 3

  minio:
    container_name: milvus-minio
    image: minio/minio:RELEASE.2023-03-20T20-16-18Z
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    ports:
      - "9001:9001"
      - "9000:9000"
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/minio:/minio_data
    command: minio server /minio_data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  standalone:
    container_name: milvus-standalone
    image: milvusdb/milvus:v2.4.0
    command: ["milvus", "run", "standalone"]
    security_opt:
    - seccomp:unconfined
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
      proxy.maxRoleNum: 200
      common.security.authorizationEnabled: "false"
    volumes:
    - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/milvus:/var/lib/milvus
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9091/healthz"]
      interval: 30s
      start_period: 90s
      timeout: 20s
      retries: 3
    ports:
      - "19530:19530"
      - "9091:9091"
    depends_on:
      - "etcd"
      - "minio"

networks:
  default:
    name: milvus
```

**Comment by xiaoToby** [comment]
So, this issue was closed, do you have some solutions for that issue ? @ligjn
