### ISSUE TITLE
[BUG] ping() got an unexpected keyword argument 'max_retry' when using http handler

### ISSUE THREAD

**Issue by del-zhenwu** [milvus-io/pymilvus#215]
**Describe the bug**
```
[2020-05-29 13:05:08-ERROR-root]: ping() got an unexpected keyword argument 'max_retry' (conftest.py:48)
[2020-05-29 13:05:08-ERROR-root]: Traceback (most recent call last):
  File "/home/zw/work/z/milvus/tests/milvus_python_test/conftest.py", line 46, in connect
    milvus = get_milvus(host=ip, port=port, handler=handler)
  File "/home/zw/work/z/milvus/tests/milvus_python_test/utils.py", line 36, in get_milvus
    milvus = Milvus(host=host, port=port, handler=handler, try_connect=try_connect)
  File "/usr/local/lib/python3.6/dist-packages/milvus/client/stub.py", line 88, in __init__
    self._pool = ConnectionPool(pool_uri, **pool_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/milvus/client/pool.py", line 85, in __init__
    self._prepare()
  File "/usr/local/lib/python3.6/dist-packages/milvus/client/pool.py", line 91, in _prepare
    conn.client().ping(max_retry=self._max_retry)
TypeError: ping() got an unexpected keyword argument 'max_retry'
```
**Steps/Code to reproduce behavior**
using `handler=HTTP`

**Expected behavior**

**Environment details**

pymilvus-test (0.3.21)

**Screenshots**

**Additional context**

**Comment by del-zhenwu** [comment]
fixed and close
