### ISSUE TITLE
[Bug]: The error message is not clear enough when inserting rows

### ISSUE THREAD

**Issue by xiaocai2333** [milvus-io/pymilvus#2154]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

```
>>> collection.insert(data)
RPC error: [insert_rows], <DataNotMatchException: (code=1, message=Attempt to insert an unexpected field to collection without enabling dynamic field)>, <Time:{'RPC start': '2023-10-11 11:12:20.341396', 'RPC error': '2023-10-11 11:12:20.341801'}>
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/zilliz/virtual-environment/milvus/lib/python3.11/site-packages/pymilvus/orm/collection.py", line 508, in insert
    res = conn.insert_rows(
          ^^^^^^^^^^^^^^^^^
  File "/Users/zilliz/virtual-environment/milvus/lib/python3.11/site-packages/pymilvus/decorators.py", line 129, in handler
    raise e from e
  File "/Users/zilliz/virtual-environment/milvus/lib/python3.11/site-packages/pymilvus/decorators.py", line 125, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zilliz/virtual-environment/milvus/lib/python3.11/site-packages/pymilvus/decorators.py", line 164, in handler
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zilliz/virtual-environment/milvus/lib/python3.11/site-packages/pymilvus/decorators.py", line 104, in handler
    raise e from e
  File "/Users/zilliz/virtual-environment/milvus/lib/python3.11/site-packages/pymilvus/decorators.py", line 68, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zilliz/virtual-environment/milvus/lib/python3.11/site-packages/pymilvus/client/grpc_handler.py", line 505, in insert_rows
    request = self._prepare_row_insert_request(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zilliz/virtual-environment/milvus/lib/python3.11/site-packages/pymilvus/client/grpc_handler.py", line 486, in _prepare_row_insert_request
    return Prepare.row_insert_param(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zilliz/virtual-environment/milvus/lib/python3.11/site-packages/pymilvus/client/prepare.py", line 423, in row_insert_param
    return cls._parse_row_request(request, fields_info, enable_dynamic, entities)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zilliz/virtual-environment/milvus/lib/python3.11/site-packages/pymilvus/client/prepare.py", line 371, in _parse_row_request
    raise DataNotMatchException(message=ExceptionsMessage.InsertUnexpectedField)
pymilvus.exceptions.DataNotMatchException: <DataNotMatchException: (code=1, message=Attempt to insert an unexpected field to collection without enabling dynamic field)>
```

### Environment details

```markdown
- Hardware/Softward conditions (OS, CPU, GPU, Memory):
- Method of installation (Docker, or from source):
- Milvus version (v0.3.1, or v0.4.0):
- Milvus configuration (Settings you made in `server_config.yaml`):
```

**Comment by xiaocai2333** [comment]
```
>>> # 1. insert data
>>> collection.insert(data)
RPC error: [insert_rows], <DataNotMatchException: (code=1, message=The data in the same column must be of the same type.)>, <Time:{'RPC start': '2023-10-20 17:27:00.366133', 'RPC error': '2023-10-20 17:27:00.367069'}>
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/homebrew/lib/python3.11/site-packages/pymilvus/orm/collection.py", line 509, in insert
    res = conn.insert_rows(
          ^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pymilvus/decorators.py", line 129, in handler
    raise e from e
  File "/opt/homebrew/lib/python3.11/site-packages/pymilvus/decorators.py", line 125, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pymilvus/decorators.py", line 164, in handler
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pymilvus/decorators.py", line 104, in handler
    raise e from e
  File "/opt/homebrew/lib/python3.11/site-packages/pymilvus/decorators.py", line 68, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pymilvus/client/grpc_handler.py", line 504, in insert_rows
    request = self._prepare_row_insert_request(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pymilvus/client/grpc_handler.py", line 485, in _prepare_row_insert_request
    return Prepare.row_insert_param(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pymilvus/client/prepare.py", line 423, in row_insert_param
    return cls._parse_row_request(request, fields_info, enable_dynamic, entities)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pymilvus/client/prepare.py", line 386, in _parse_row_request
    raise DataNotMatchException(message=ExceptionsMessage.DataTypeInconsistent) from e
pymilvus.exceptions.DataNotMatchException: <DataNotMatchException: (code=1, message=The data in the same column must be of the same type.)>
>>> 
```

**Comment by xiaocai2333** [comment]
open it with milvus issue: https://github.com/milvus-io/milvus/issues/27628

**Comment by Elijas** [comment]
Do you happen to have any updates on this?

**Comment by arijitthehacker** [comment]
Same error. Is there any updates on the package?
