### ISSUE TITLE
[Bug]: create index on json field is not supported: expected=supported field

### ISSUE THREAD

**Issue by LouisHeck** [milvus-io/pymilvus#2155]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When I do "hello_hybrid_sparse_dense.py"(https://github.com/milvus-io/pymilvus/blob/0318663b84e1efe19d22b356ff067df6ee4fd61c/examples/hello_hybrid_sparse_dense.py#L94)，

Relation Codes below:

```
# We need to create indices for the vector fields. The indices will be loaded
# into memory for efficient search.
dense_index = {"index_type": "FLAT", "metric_type": "IP"}
col.create_index("dense_vector", dense_index)
sparse_index = {"index_type": "SPARSE_INVERTED_INDEX", "metric_type": "IP"}
col.create_index("sparse_vector", sparse_index)

col.load()
```

Raise a MilvusException： 

```
 RPC error: [create_index], <MilvusException: (code=1100, message=create index on json field is not supported: expected=supported field, actual=create index on 104 field: invalid parameter)>, <Time:{'RPC start': '2024-06-27 09:54:21.879815', 'RPC error': '2024-06-27 09:54:21.935001'}>
Traceback (most recent call last):
  File "/mnt/d/2024Project/hybrid_search/add_hybrid_data/add_docs_hybrid.py", line 64, in <module>
    col.create_index("sparse_vector", sparse_index)
  File "/root/miniconda3/envs/ai-app-service/lib/python3.9/site-packages/pymilvus/orm/collection.py", line 1367, in create_index
    return conn.create_index(self._name, field_name, index_params, timeout=timeout, **kwargs)
  File "/root/miniconda3/envs/ai-app-service/lib/python3.9/site-packages/pymilvus/decorators.py", line 147, in handler
    raise e from e
  File "/root/miniconda3/envs/ai-app-service/lib/python3.9/site-packages/pymilvus/decorators.py", line 143, in handler
    return func(*args, **kwargs)
  File "/root/miniconda3/envs/ai-app-service/lib/python3.9/site-packages/pymilvus/decorators.py", line 182, in handler
    return func(self, *args, **kwargs)
  File "/root/miniconda3/envs/ai-app-service/lib/python3.9/site-packages/pymilvus/decorators.py", line 122, in handler
    raise e from e
  File "/root/miniconda3/envs/ai-app-service/lib/python3.9/site-packages/pymilvus/decorators.py", line 87, in handler
    return func(*args, **kwargs)
  File "/root/miniconda3/envs/ai-app-service/lib/python3.9/site-packages/pymilvus/client/grpc_handler.py", line 987, in create_index
    check_status(status)
  File "/root/miniconda3/envs/ai-app-service/lib/python3.9/site-packages/pymilvus/client/utils.py", line 63, in check_status
    raise MilvusException(status.code, status.reason, status.error_code)
pymilvus.exceptions.MilvusException: <MilvusException: (code=1100, message=**create index on json field is not supported: expected=supported field**, actual=create index on 104 field: invalid parameter)>

Process finished with exit code 1

```

My Current Env:

milvus version: milvusdb/milvus:v2.4.0-rc.1
pymilvus version: Version: 2.4.4

What's the problem? How to solve it? Many Thanks.

### Environment details

```markdown
milvus version: milvusdb/milvus:v2.4.0-rc.1
pymilvus version: Version: 2.4.4
```

**Comment by SimFG** [comment]
@LouisHeck Can you show how you created the collection? According to this error message, it seems that the index type is applied to the wrong data type.

**Comment by LouisHeck** [comment]
> @LouisHeck Can you show how you created the collection? According to this error message, it seems that the index type is applied to the wrong data type.

Okay, Below is the code.

```
import random
import string
import numpy as np

from pymilvus import (
    utility,
    FieldSchema, CollectionSchema, DataType,
    Collection, AnnSearchRequest, RRFRanker, connections,
)

# 1. prepare a small corpus to search
from embeddings_api import hybrid_embed_texts

docs = [
    "Artificial intelligence was founded as an academic discipline in 1956.",
    "Alan Turing was the first person to conduct substantial research in AI.",
    "Born in Maida Vale, London, Turing was raised in southern England.",
]
# add some randomly generated texts
docs.extend([' '.join(''.join(random.choice(string.ascii_lowercase) for _ in range(random.randint(1, 8))) for _ in range(10)) for _ in range(1000)])
query = "Who started AI research?"

dense_dim = 1024
ef = hybrid_embed_texts

docs_embeddings = ef(docs)
query_embeddings = ef([query])

# 2. setup Milvus collection and index
connections.connect(uri="http://localhost:19530", user="root", password="****",)

# Specify the data schema for the new Collection.
fields = [
    # Use auto generated id as primary key
    FieldSchema(name="pk", dtype=DataType.VARCHAR,
                is_primary=True, auto_id=False, max_length=100),
    # Store the original text to retrieve based on semantically distance
    FieldSchema(name="text", dtype=DataType.VARCHAR, max_length=10000),
    # Milvus now supports both sparse and dense vectors, we can store each in
    # a separate field to conduct hybrid search on both vectors.
    FieldSchema(name="sparse_vector", dtype=DataType.SPARSE_FLOAT_VECTOR),
    FieldSchema(name="dense_vector", dtype=DataType.FLOAT_VECTOR,
                dim=dense_dim),
]
schema = CollectionSchema(fields, "")
col_name = 'hybrid_demo'
# Now we can create the new collection with above name and schema.
col = Collection(col_name, schema, consistency_level="Strong")

# We need to create indices for the vector fields. The indices will be loaded
# into memory for efficient search.
dense_index = {"index_type": "FLAT", "metric_type": "IP"}
col.create_index("dense_vector", dense_index)
sparse_index = {"index_type": "SPARSE_FLOAT_VECTOR", "metric_type": "IP"}
# sparse_index = {"index_type": "FLAT", "metric_type": "IP", "params": {"M": 8, "efConstruction": 100}}

col.create_index("sparse_vector", sparse_index)

col.load()
```

**Comment by SimFG** [comment]
@LouisHeck I am using the latest version of milvus and this error does not appear. And, based on the code you provided, it seems that the error stack does not match, because the issue describes that there is a problem with the fifth field, but the demo code provided does not seem to have this field.

**Comment by LouisHeck** [comment]
> @LouisHeck I am using the latest version of milvus and this error does not appear. And, based on the code you provided, it seems that the error stack does not match, because the issue describes that there is a problem with the fifth field, but the demo code provided does not seem to have this field.

@SimFG it might not related by fifth field, the error from line "col.create_index("sparse_vector", sparse_index)", it might because of creating sparse index error.

here is the full code I debug currently.

```
# A demo showing hybrid semantic search with dense and sparse vectors using Milvus.
#
# You can optionally choose to use the BGE-M3 model to embed the text as dense
# and sparse vectors, or simply use random generated vectors as an example.
#
# You can also use the BGE CrossEncoder model to rerank the search results.
#
# Note that the sparse vector search feature is only available in Milvus 2.4.0 or
# higher version. Make sure you follow https://milvus.io/docs/install_standalone-docker.md
# to set up the latest version of Milvus in your local environment.

# To connect to Milvus server, you need the python client library called pymilvus.
# To use BGE-M3 model, you need to install the optional `model` module in pymilvus.
# You can get them by simply running the following commands:
#
# pip install pymilvus
# pip install pymilvus[model]

# If true, use BGE-M3 model to generate dense and sparse vectors.
# If false, use random numbers to compose dense and sparse vectors.
use_bge_m3 = False
# If true, the search result will be reranked using BGE CrossEncoder model.
use_reranker = False

# The overall steps are as follows:
# 1. embed the text as dense and sparse vectors
# 2. setup a Milvus collection to store the dense and sparse vectors
# 3. insert the data to Milvus
# 4. search and inspect the result!
import random
import string
import numpy as np

from pymilvus import (
    utility,
    FieldSchema, CollectionSchema, DataType,
    Collection, AnnSearchRequest, RRFRanker, connections,
)

# 1. prepare a small corpus to search
docs = [
    "Artificial intelligence was founded as an academic discipline in 1956.",
    "Alan Turing was the first person to conduct substantial research in AI.",
    "Born in Maida Vale, London, Turing was raised in southern England.",
]
# add some randomly generated texts
docs.extend([' '.join(''.join(random.choice(string.ascii_lowercase) for _ in range(random.randint(1, 8))) for _ in range(10)) for _ in range(1000)])
query = "Who started AI research?"

def random_embedding(texts):
    rng = np.random.default_rng()
    return {
        "dense": np.random.rand(len(texts), 768),
        "sparse": [{d: rng.random() for d in random.sample(range(1000), random.randint(20, 30))} for _ in texts],
    }

dense_dim = 768
ef = random_embedding

docs_embeddings = ef(docs)
query_embeddings = ef([query])

# 2. setup Milvus collection and index
connections.connect("default", uri="http://43.139.62.171:19530", user="root", password="Ndyl6V3S8zVa7X",)

# Specify the data schema for the new Collection.
fields = [
    # Use auto generated id as primary key
    FieldSchema(name="pk", dtype=DataType.VARCHAR,
                is_primary=True, auto_id=True, max_length=100),
    # Store the original text to retrieve based on semantically distance
    FieldSchema(name="text", dtype=DataType.VARCHAR, max_length=512),
    # Milvus now supports both sparse and dense vectors, we can store each in
    # a separate field to conduct hybrid search on both vectors.
    FieldSchema(name="sparse_vector", dtype=DataType.SPARSE_FLOAT_VECTOR),
    FieldSchema(name="dense_vector", dtype=DataType.FLOAT_VECTOR,
                dim=dense_dim),
]
schema = CollectionSchema(fields, "")
col_name = 'hybrid_demo'

# Now we can create the new collection with above name and schema.
col = Collection(col_name, schema, consistency_level="Strong")

# We need to create indices for the vector fields. The indices will be loaded
# into memory for efficient search.
sparse_index = {"index_type": "SPARSE_INVERTED_INDEX", "metric_type": "IP"}
col.create_index("sparse_vector", sparse_index)
dense_index = {"index_type": "FLAT", "metric_type": "IP"}
col.create_index("dense_vector", dense_index)
col.load()

# # 3. insert text and sparse/dense vector representations into the collection
# entities = [docs, docs_embeddings["sparse"], docs_embeddings["dense"]]
# col.insert(entities)
# col.flush()
#
# # 4. search and inspect the result!
# k = 2 # we want to get the top 2 docs closest to the query
#
# # Prepare the search requests for both vector fields
# sparse_search_params = {"metric_type": "IP"}
# sparse_req = AnnSearchRequest(query_embeddings["sparse"],
#                               "sparse_vector", sparse_search_params, limit=k)
# dense_search_params = {"metric_type": "IP"}
# dense_req = AnnSearchRequest(query_embeddings["dense"],
#                              "dense_vector", dense_search_params, limit=k)
#
# # Search topK docs based on dense and sparse vectors and rerank with RRF.
# res = col.hybrid_search([sparse_req, dense_req], rerank=RRFRanker(),
#                         limit=k, output_fields=['text'])
#
# # Currently Milvus only support 1 query in the same hybrid search request, so
# # we inspect res[0] directly. In future release Milvus will accept batch
# # hybrid search queries in the same call.
# res = res[0]
#
# if use_reranker:
#     result_texts = [hit.fields["text"] for hit in res]
#     from pymilvus.model.reranker import BGERerankFunction
#     bge_rf = BGERerankFunction(device='cpu')
#     # rerank the results using BGE CrossEncoder model
#     results = bge_rf(query, result_texts, top_k=2)
#     for hit in results:
#         print(f'text: {hit.text} distance {hit.score}')
# else:
#     for hit in res:
#         print(f'text: {hit.fields["text"]} distance {hit.distance}')
#
# # If you used both BGE-M3 and the reranker, you should see the following:
# # text: Alan Turing was the first person to conduct substantial research in AI. distance 0.9306981017573297
# # text: Artificial intelligence was founded as an academic discipline in 1956. distance 0.03217001154515051
# #
# # If you used only BGE-M3, you should see the following:
# # text: Alan Turing was the first person to conduct substantial research in AI. distance 0.032786883413791656
# # text: Artificial intelligence was founded as an academic discipline in 1956. distance 0.016129031777381897
#
# # In this simple example the reranker yields the same result as the embedding based hybrid search, but in more complex
# # scenarios the reranker can provide more accurate results.
#
# # If you used random vectors, the result will be different each time you run the script.
#
# # Drop the collection to clean up the data.
# utility.drop_collection(col_name)
```

and the Error Messages below:

```
RPC error: [create_index], <MilvusException: (code=1100, message=create index on json field is not supported: expected=supported field, actual=create index on 104 field: invalid parameter)>, <Time:{'RPC start': '2024-06-27 18:42:17.864420', 'RPC error': '2024-06-27 18:42:17.907069'}>
Traceback (most recent call last):
  File "/mnt/d/2024Project/hybrid_search/add_hybrid_data/add_docs_hybrid_pymilvus.py", line 88, in <module>
    col.create_index("sparse_vector", sparse_index)
  File "/root/miniconda3/envs/app-service/lib/python3.9/site-packages/pymilvus/orm/collection.py", line 1367, in create_index
    return conn.create_index(self._name, field_name, index_params, timeout=timeout, **kwargs)
  File "/root/miniconda3/envs/app-service/lib/python3.9/site-packages/pymilvus/decorators.py", line 147, in handler
    raise e from e
  File "/root/miniconda3/envs/app-service/lib/python3.9/site-packages/pymilvus/decorators.py", line 143, in handler
    return func(*args, **kwargs)
  File "/root/miniconda3/envs/app-service/lib/python3.9/site-packages/pymilvus/decorators.py", line 182, in handler
    return func(self, *args, **kwargs)
  File "/root/miniconda3/envs/app-service/lib/python3.9/site-packages/pymilvus/decorators.py", line 122, in handler
    raise e from e
  File "/root/miniconda3/envs/app-service/lib/python3.9/site-packages/pymilvus/decorators.py", line 87, in handler
    return func(*args, **kwargs)
  File "/root/miniconda3/envs/app-service/lib/python3.9/site-packages/pymilvus/client/grpc_handler.py", line 987, in create_index
    check_status(status)
  File "/root/miniconda3/envs/app-service/lib/python3.9/site-packages/pymilvus/client/utils.py", line 63, in check_status
    raise MilvusException(status.code, status.reason, status.error_code)
pymilvus.exceptions.MilvusException: <MilvusException: (code=1100, message=create index on json field is not supported: expected=supported field, actual=create index on 104 field: invalid parameter)>
```

Does current version milvus do not support "SPARSE_INVERTED_INDEX"? what the reason? 
Thanks in advance!

**Comment by SimFG** [comment]
Your collection has four fields. According to the field id rules in milvus, they are 100, 101, 102, and 103, but the error indicates that the field is 104.
the milvus 2.4.0-rc1 source code: https://github.com/milvus-io/milvus/blob/7abebf81a3c6b5dc57ec216084f5c4892dec6602/internal/proxy/task_index.go#L174
release link: https://github.com/milvus-io/milvus/releases/tag/v2.4.0-rc.1
If possible, you can restart milvus and search for `GitCommit` in the log to confirm whether the version is correct.

**Comment by LouisHeck** [comment]
> Your collection has four fields. According to the field id rules in milvus, they are 100, 101, 102, and 103, but the error indicates that the field is 104. the milvus 2.4.0-rc1 source code: https://github.com/milvus-io/milvus/blob/7abebf81a3c6b5dc57ec216084f5c4892dec6602/internal/proxy/task_index.go#L174 release link: https://github.com/milvus-io/milvus/releases/tag/v2.4.0-rc.1 If possible, you can restart milvus and search for `GitCommit` in the log to confirm whether the version is correct.

@SimFG Yes, when I change to milvus 2.4.5, it works well, it's indeed my milvus version problem. Thanks again!
