### ISSUE TITLE
pymilvus fails to connect / instantiate a db server locally on AWS SageMaker

### ISSUE THREAD

**Issue by kevalshah90** [milvus-io/pymilvus#2267]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

MilvusLite doesn't work / start the server locally. Documentation suggests that local uri should start the server automatically, but it fails. Getting the same exception with `llama_index.vector_stores.MilvusVectorStore`

Environment: AWS SageMaker Notebook instance. 

```
versions:

pymilvus 2.4.6
milvus-lite 2.4.10
```

```
from pymilvus import MilvusClient

client = MilvusClient("./milvus.db")


/home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/milvus_lite/lib/milvus: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/milvus_lite/lib/milvus)
Failed to create new connection using: 5aef7778d6df45ef9ddf553a79894057

File ~/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/pymilvus/client/grpc_handler.py:150, in GrpcHandler._wait_for_channel_ready(self, timeout)
    148     self._setup_identifier_interceptor(self._user, timeout=timeout)
    149 except grpc.FutureTimeoutError as e:
--> 150     raise MilvusException(
    151         code=Status.CONNECT_FAILED,
    152         message=f"Fail connecting to server on {self._address}, illegal connection params or server unavailable",
    153     ) from e
    154 except Exception as e:
    155     raise e from e

MilvusException: <MilvusException: (code=2, message=Fail connecting to server on unix:/tmp/tmpc4s187rx_milvus.db.sock, illegal connection params or server unavailable)>
```

### Environment details

```markdown
pymilvus 2.4.6
milvus-lite 2.4.10
```

**Comment by micuentadecasa** [comment]
I'm having similar issue, any tip?

**Comment by vimalKeshu** [comment]
What's reason behind it ?
```
2025-02-06 09:12:52,970 [ERROR][_create_connection]: Failed to create new connection using: 161712c4132c4070881e940705c82287 (milvus_client.py:920)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/pymilvus/milvus_client/milvus_client.py", line 66, in __init__
    self._using = self._create_connection(
  File "/usr/local/lib/python3.9/site-packages/pymilvus/milvus_client/milvus_client.py", line 921, in _create_connection
    raise ex from ex
  File "/usr/local/lib/python3.9/site-packages/pymilvus/milvus_client/milvus_client.py", line 918, in _create_connection
    connections.connect(using, user, password, db_name, token, uri=uri, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/pymilvus/orm/connections.py", line 461, in connect
    connect_milvus(**kwargs, user=user, password=password, token=token, db_name=db_name)
  File "/usr/local/lib/python3.9/site-packages/pymilvus/orm/connections.py", line 411, in connect_milvus
    gh._wait_for_channel_ready(timeout=timeout)
  File "/usr/local/lib/python3.9/site-packages/pymilvus/client/grpc_handler.py", line 152, in _wait_for_channel_ready
    raise MilvusException(
pymilvus.exceptions.MilvusException: <MilvusException: (code=2, message=Fail connecting to server on unix:/tmp/tmp_dgwgv4k_milvus_production_2.db.sock, illegal connection params or server unavailable)>
```
