### ISSUE TITLE
[Bug]: AmbiguousIndexName when create local vectorStore

### ISSUE THREAD

**Issue by ezscode** [milvus-io/pymilvus#2271]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I try to create local vectorStore following  <https://milvus.io/docs/zh/integrate_with_llamaindex.md> 

```python
vector_store = MilvusVectorStore(uri="./milvus_demo.db", dim=1536, overwrite=True)
```
But got error :

```shell
RPC error: [describe_index], <AmbiguousIndexName: (code=1, message=There are multiple indexes, please specify the index_name.)>, <Time:{'RPC start': '2024-09-24 09:29:48.706720', 'RPC error': '2024-09-24 09:29:48.707154'}>
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/pc087/miniconda3/lib/python3.11/site-packages/llama_index/vector_stores/milvus/base.py", line 306, in __init__
    self._create_index_if_required()
  File "/Users/pc087/miniconda3/lib/python3.11/site-packages/llama_index/vector_stores/milvus/base.py", line 790, in _create_index_if_required
    self._create_dense_index()
  File "/Users/pc087/miniconda3/lib/python3.11/site-packages/llama_index/vector_stores/milvus/base.py", line 801, in _create_dense_index
    index_exists = self._collection.has_index()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pc087/miniconda3/lib/python3.11/site-packages/pymilvus/orm/collection.py", line 1451, in has_index
    conn.describe_index(self._name, index_name, timeout=timeout, **copy_kwargs) is not None
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pc087/miniconda3/lib/python3.11/site-packages/pymilvus/decorators.py", line 148, in handler
    raise e from e
  File "/Users/pc087/miniconda3/lib/python3.11/site-packages/pymilvus/decorators.py", line 144, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pc087/miniconda3/lib/python3.11/site-packages/pymilvus/decorators.py", line 183, in handler
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pc087/miniconda3/lib/python3.11/site-packages/pymilvus/decorators.py", line 123, in handler
    raise e from e
  File "/Users/pc087/miniconda3/lib/python3.11/site-packages/pymilvus/decorators.py", line 87, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pc087/miniconda3/lib/python3.11/site-packages/pymilvus/client/grpc_handler.py", line 1063, in describe_index
    raise AmbiguousIndexName(message=ExceptionsMessage.AmbiguousIndexName)
pymilvus.exceptions.AmbiguousIndexName: <AmbiguousIndexName: (code=1, message=There are multiple indexes, please specify the index_name.)>
>>> 
```

***

What's wrong with it ?
How to create local vectorStore ?

### Expected Behavior

I want to create a milvus_demo.db locally.

### Steps/Code To Reproduce behavior

```markdown
from llama_index.core import VectorStoreIndex, StorageContext
from llama_index.vector_stores.milvus import MilvusVectorStore


vector_store = MilvusVectorStore(
    uri="./milvus_demo.db", dim=1536, overwrite=True
)
```

### Environment details

```markdown
- macOS M2 14.3 
- pip install pymilvus ( 2.4.6 )
```

### Anything else?

I try to connect `localhost:19530` and successed。

**Comment by axhiao** [comment]
I think this is a bug. But I found a solution with below setting:

```python
from pymilvus.settings import Config
Config.IndexName = "vector"
```
