### ISSUE TITLE
[Bug]: Missing attributes when using LocalBulkWriter

### ISSUE THREAD

**Issue by Stevan1996** [milvus-io/pymilvus#2274]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I am trying to use the LocalBulkWriter. When initializing the LocalBulkWriter, I get the following error message. I followed this user guide: https://milvus.io/docs/prepare-source-data.md
```
    writer = LocalBulkWriter(schema=schema, local_path=".", file_type=BulkFileType.JSON)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steven/.conda/envs/dpm/lib/python3.11/site-packages/pymilvus/bulk_writer/local_bulk_writer.py", line 42, in __init__
    super().__init__(schema, chunk_size, file_type, **kwargs)
  File "/home/steven/.conda/envs/dpm/lib/python3.11/site-packages/pymilvus/bulk_writer/bulk_writer.py", line 57, in __init__
    if len(self._schema.fields) == 0:
           ^^^^^^^^^^^^^^^^^^^
AttributeError: 'function' object has no attribute 'fields'
Exception ignored in: <function LocalBulkWriter.__del__ at 0x707a78d6fba0>
Traceback (most recent call last):
  File "/home/steven/.conda/envs/dpm/lib/python3.11/site-packages/pymilvus/bulk_writer/local_bulk_writer.py", line 63, in __del__
    self._exit()
  File "/home/steven/.conda/envs/dpm/lib/python3.11/site-packages/pymilvus/bulk_writer/local_bulk_writer.py", line 67, in _exit
    if len(self._working_thread) > 0:
           ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'LocalBulkWriter' object has no attribute '_working_thread'
```

### Environment details

```markdown
- pymilvus: 2.4.6
- protobuf: 5.28.2
- grpcio: 1.66.1
```

**Comment by yhmo** [comment]
self._schema of BulkWriter is a CollectionSchema
The attribute "fields" is defined here: https://github.com/milvus-io/pymilvus/blob/b3e8cbf1c1be53cf05b37284c234c580c5e2bf2e/pymilvus/orm/schema.py#L87

self._working_thread of LocalBulkWriter is defined here: https://github.com/milvus-io/pymilvus/blob/b3e8cbf1c1be53cf05b37284c234c580c5e2bf2e/pymilvus/bulk_writer/local_bulk_writer.py#L46

The code is clear and no problem, I have no idea why you got the error.

**Comment by yhmo** [comment]
The fill script of the [doc](https://milvus.io/docs/prepare-source-data.md):
It works fine and correct.
```
from pymilvus import MilvusClient, DataType

schema = MilvusClient.create_schema(
    auto_id=False,
    enable_dynamic_field=True
)

schema.add_field(field_name="id", datatype=DataType.INT64, is_primary=True)
schema.add_field(field_name="vector", datatype=DataType.FLOAT_VECTOR, dim=768)
schema.add_field(field_name="scalar_1", datatype=DataType.VARCHAR, max_length=512)
schema.add_field(field_name="scalar_2", datatype=DataType.INT64)

schema.verify()


from pymilvus.bulk_writer import LocalBulkWriter, BulkFileType

writer = LocalBulkWriter(
    schema=schema,
    local_path='.',
    segment_size=512 * 1024 * 1024, # Default value
    file_type=BulkFileType.PARQUET
)

import random
import string


def generate_random_str(length=5):
    letters = string.ascii_uppercase
    digits = string.digits

    return ''.join(random.choices(letters + digits, k=length))


for i in range(10000):
    writer.append_row({
        "id": i,
        "vector": [random.uniform(-1, 1) for _ in range(768)],
        "scalar_1": generate_random_str(random.randint(1, 20)),
        "scalar_2": random.randint(0, 100)
    })

writer.commit()

import random
import string


def generate_random_string(length=5):
    letters = string.ascii_uppercase
    digits = string.digits

    return ''.join(random.choices(letters + digits, k=length))


for i in range(10000):
    writer.append_row({
        "id": i,
        "vector": [random.uniform(-1, 1) for _ in range(768)],
        "scalar_1": generate_random_string(),
        "scalar_2": random.randint(0, 100),
        "dynamic_field_1": random.choice([True, False]),
        "dynamic_field_2": random.randint(0, 100)
    })

writer.commit()


print(writer.batch_files)

```
The output is two files path:
`[['d9952a00-8600-43a7-9ffa-ef5f601b2588/1.parquet'], ['d9952a00-8600-43a7-9ffa-ef5f601b2588/2.parquet']]`

**Comment by Stevan1996** [comment]
Thanks for your help. For some reason, I don't get the error message anymore. I can't figure out what's different this time.
