### ISSUE TITLE
[Bug]: Why do i get "ImportError: sys.meta_path is None, Python is likely shutting down" when trying to run Milvus

### ISSUE THREAD

**Issue by VanechikSpace** [milvus-io/pymilvus#2282]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When i run the following code:
```
from pymilvus import MilvusClient

client = MilvusClient("milvus.db")
print("hello")
```
i see the following result:
```
hello
Exception ignored in: <function ServerManager.__del__ at 0x7f3d1f9a2f20>
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/milvus_lite/server_manager.py", line 58, in __del__
  File "/usr/local/lib/python3.12/dist-packages/milvus_lite/server_manager.py", line 53, in release_all
  File "/usr/local/lib/python3.12/dist-packages/milvus_lite/server.py", line 118, in stop
  File "/usr/lib/python3.12/pathlib.py", line 1164, in __init__
  File "/usr/lib/python3.12/pathlib.py", line 358, in __init__
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function Server.__del__ at 0x7f3d1f9a2d40>
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/milvus_lite/server.py", line 122, in __del__
  File "/usr/local/lib/python3.12/dist-packages/milvus_lite/server.py", line 118, in stop
  File "/usr/lib/python3.12/pathlib.py", line 1164, in __init__
  File "/usr/lib/python3.12/pathlib.py", line 358, in __init__
ImportError: sys.meta_path is None, Python is likely shutting down
```

**qwer.db** file is created but i don't want to get this error

### Environment details

```markdown
- Method of installation (Docker, or from source): sudo pip install pymilvus pymilvus[model] pymilvus[bulk_writer] --break-system-packages

- pymilvus version: 2.4.7
```

### Anything else?

I tried to run this code:
```
from pymilvus import MilvusClient

try:
    client = MilvusClient("qwer.db")
finally:
    client.close()
```

but the result is the same.

**Comment by XuanYang-cn** [comment]
Looks like an issue of Milvus-lite

**Comment by junjiejiangjjj** [comment]
hi @VanechikSpace , I run it with `Python 3.12.4` and it works fine. You can use conda to recreate a Python 3.12 environment and try it.

**Comment by dnns92** [comment]
I have the same issue on this environment:

~~~bash
Python 3.12.3
milvus-lite==2.4.10
pymilvus==2.4.9
~~~

**Comment by yhdelgado** [comment]
I have the same issue on this environment:

```
Python 3.12.3
milvus-lite==2.4.11
pymilvus==2.5.4
```
