### ISSUE TITLE
[Bug]: code=1100, create index on json field is not supported: expected=supported field, actual=create index on 104 field

### ISSUE THREAD

**Issue by luc42ei** [milvus-io/pymilvus#2324]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

It's actually the exact same issue as w/  #2155. However, the solution doesn't work for me. It seem like using pymilvus version 2.4.5 should resolve the issue but it doesn't. Before I was on 2.4.9 and it also wasn't working.

Am I missing something? Shouldn't newer versions contain the solutions of older problems? (But it's not even a “solution” in this case.)

I also don't understand the error message. Where is the JSON field? Is a sparse vector a JSON field?

### Steps/Code To Reproduce behavior

```markdown
import random
import string

import numpy as np
from pymilvus import Collection, CollectionSchema, DataType, FieldSchema, connections

# 1. prepare a small corpus to search
docs = [
    "Artificial intelligence was founded as an academic discipline in 1956.",
    "Alan Turing was the first person to conduct substantial research in AI.",
    "Born in Maida Vale, London, Turing was raised in southern England.",
]
# add some randomly generated texts
docs.extend([' '.join(''.join(random.choice(string.ascii_lowercase) for _ in range(random.randint(1, 8))) for _ in range(10)) for _ in range(1000)])
query = "Who started AI research?"

def random_embedding(texts):
    rng = np.random.default_rng()
    return {
        "dense": np.random.rand(len(texts), 768),
        "sparse": [{d: rng.random() for d in random.sample(range(1000), random.randint(20, 30))} for _ in texts],
    }

dense_dim = 768
ef = random_embedding

docs_embeddings = ef(docs)
query_embeddings = ef([query])

# 2. setup Milvus collection and index
connections.connect("default", host="localhost", port="19530")

fields = [
    FieldSchema(name="pk", dtype=DataType.VARCHAR, is_primary=True, auto_id=True, max_length=100),
    FieldSchema(name="text", dtype=DataType.VARCHAR, max_length=512),
    FieldSchema(name="sparse_vector", dtype=DataType.SPARSE_FLOAT_VECTOR),
    FieldSchema(name="dense_vector", dtype=DataType.FLOAT_VECTOR, dim=dense_dim),
]
schema = CollectionSchema(fields, "")
collection = Collection('hybrid_demo', schema, consistency_level="Strong")

sparse_index = {"index_type": "SPARSE_INVERTED_INDEX", "metric_type": "IP"}
collection.create_index("sparse_vector", sparse_index)
```
last line produces this error message:
```
Traceback (most recent call last):
  File "/home/lucas/Documents/StefanArbeit/RAG/docpilot/tmp/hello_hybrid_sparse_dense.py", line 43, in <module>
    collection.create_index("sparse_vector", sparse_index)
  File "/home/lucas/.cache/pypoetry/virtualenvs/docpilot-bHe3KMyn-py3.11/lib/python3.11/site-packages/pymilvus/orm/collection.py", line 1373, in create_index
    return conn.create_index(self._name, field_name, index_params, timeout=timeout, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/.cache/pypoetry/virtualenvs/docpilot-bHe3KMyn-py3.11/lib/python3.11/site-packages/pymilvus/decorators.py", line 148, in handler
    raise e from e
  File "/home/lucas/.cache/pypoetry/virtualenvs/docpilot-bHe3KMyn-py3.11/lib/python3.11/site-packages/pymilvus/decorators.py", line 144, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/.cache/pypoetry/virtualenvs/docpilot-bHe3KMyn-py3.11/lib/python3.11/site-packages/pymilvus/decorators.py", line 183, in handler
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/.cache/pypoetry/virtualenvs/docpilot-bHe3KMyn-py3.11/lib/python3.11/site-packages/pymilvus/decorators.py", line 123, in handler
    raise e from e
  File "/home/lucas/.cache/pypoetry/virtualenvs/docpilot-bHe3KMyn-py3.11/lib/python3.11/site-packages/pymilvus/decorators.py", line 87, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/.cache/pypoetry/virtualenvs/docpilot-bHe3KMyn-py3.11/lib/python3.11/site-packages/pymilvus/client/grpc_handler.py", line 987, in create_index
    check_status(status)
  File "/home/lucas/.cache/pypoetry/virtualenvs/docpilot-bHe3KMyn-py3.11/lib/python3.11/site-packages/pymilvus/client/utils.py", line 63, in check_status
    raise MilvusException(status.code, status.reason, status.error_code)
pymilvus.exceptions.MilvusException: <MilvusException: (code=1100, message=create index on json field is not supported: expected=supported field, actual=create index on 104 field: invalid parameter)>
```
```


### Environment details

```markdown
- Debian 12
- milvus-standalone (Docker)
- Milvus version: 2.4.9
```

**Comment by luc42ei** [comment]
the same happens when executing the code [sparse.py](https://github.com/milvus-io/pymilvus/blob/master/examples/milvus_client/sparse.py)
and executing the example code from [Sparse Vector](https://milvus.io/docs/sparse_vector.md#Prepare-sparse-vector-embeddings) also doesn't work

**Comment by luc42ei** [comment]
I found out that my milvus version was actually 2.3.3, not 2.4.9 which was the pymilvus version, but not Milvus!!
