### ISSUE TITLE
[Bug]: "only IP is the supported metric type for sparse index"

### ISSUE THREAD

**Issue by luc42ei** [milvus-io/pymilvus#2400]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When I go through the example code on [Full Text Search](https://milvus.io/docs/full-text-search.md), or the [example on BM25](https://github.com/milvus-io/pymilvus/blob/master/examples/bm25.py) or the [example on hybrid search w/ BM25](https://github.com/milvus-io/pymilvus/blob/master/examples/hybrid_search/hello_hybrid_bm25.py), I get this error:
```
RPC error: [create_index], <MilvusException: (code=1100, message=only IP is the supported metric type for sparse index: invalid parameter[expected=valid index params][actual=invalid index params])>, <Time:{'RPC start': '2024-12-02 16:12:32.746070', 'RPC error': '2024-12-02 16:12:32.749947'}>
Traceback (most recent call last):
  File "/home/lucas/Documents/StefanArbeit/RAG/docpilot/tmp/hello_hybrid_bm25.py", line 118, in <module>
    col.create_index("sparse_vector", sparse_index)
  File "/home/lucas/.cache/pypoetry/virtualenvs/docpilot-bHe3KMyn-py3.11/lib/python3.11/site-packages/pymilvus/orm/collection.py", line 1373, in create_index
    return conn.create_index(self._name, field_name, index_params, timeout=timeout, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/.cache/pypoetry/virtualenvs/docpilot-bHe3KMyn-py3.11/lib/python3.11/site-packages/pymilvus/decorators.py", line 141, in handler
    raise e from e
  File "/home/lucas/.cache/pypoetry/virtualenvs/docpilot-bHe3KMyn-py3.11/lib/python3.11/site-packages/pymilvus/decorators.py", line 137, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/.cache/pypoetry/virtualenvs/docpilot-bHe3KMyn-py3.11/lib/python3.11/site-packages/pymilvus/decorators.py", line 176, in handler
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/.cache/pypoetry/virtualenvs/docpilot-bHe3KMyn-py3.11/lib/python3.11/site-packages/pymilvus/decorators.py", line 116, in handler
    raise e from e
  File "/home/lucas/.cache/pypoetry/virtualenvs/docpilot-bHe3KMyn-py3.11/lib/python3.11/site-packages/pymilvus/decorators.py", line 86, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/.cache/pypoetry/virtualenvs/docpilot-bHe3KMyn-py3.11/lib/python3.11/site-packages/pymilvus/client/grpc_handler.py", line 991, in create_index
    check_status(status)
  File "/home/lucas/.cache/pypoetry/virtualenvs/docpilot-bHe3KMyn-py3.11/lib/python3.11/site-packages/pymilvus/client/utils.py", line 63, in check_status
    raise MilvusException(status.code, status.reason, status.error_code)
pymilvus.exceptions.MilvusException: <MilvusException: (code=1100, message=only IP is the supported metric type for sparse index: invalid parameter[expected=valid index params][actual=invalid index params])>
```
Seems like the BM25 metric type is not yet implemented?

**Comment by zhengbuqian** [comment]
hi @luc42ei , Full Text Search is a new feature in the 2.5 version of Milvus, please make sure you are using the correct version. 2.5 has not been officially released yet but we do have a beta version to be tried out https://github.com/milvus-io/milvus/releases/tag/v2.5.0-beta.
