### ISSUE TITLE
[Bug]: AsyncMilvusClient db_name doesn't take effect

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/pymilvus#2468]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

1. create db 'zong'
2. init AsyncMilvusClient with db_name="zong"
3. AsyncMilvusClient create collection 'hello_milvus'
4. expected 'hello_milvus' in db 'zong', actually it in 'default' db
```
from pymilvus import (
    DataType,
    MilvusClient,
    AsyncMilvusClient,
)
import numpy as np
import asyncio
from util_log import test_log as log

#
num_entities, dim = 10000, 128
nq, default_limit = 2, 3
collection_name = "hello_milvus"
rng = np.random.default_rng(seed=19530)
output_fields = ["pk", "random"]

uri = "http://10.104.17.186:19530"
db_name = "zong"
_client = MilvusClient(uri=uri)
if db_name not in _client.list_databases():
    _client.create_database(db_name)

_client.close()
milvus_client = MilvusClient(uri=uri, db_name=db_name)
async_milvus_client = AsyncMilvusClient(uri=uri, db_name=db_name)

loop = asyncio.get_event_loop()


# prepare collection
schema = async_milvus_client.create_schema(auto_id=False,
                                           description="hello_milvus is the simplest demo to introduce the APIs")
schema.add_field("pk", DataType.VARCHAR, is_primary=True, max_length=100)
schema.add_field("random", DataType.FLOAT)
schema.add_field("embeddings", DataType.FLOAT_VECTOR, dim=dim)
schema.add_field("embeddings2", DataType.FLOAT_VECTOR, dim=dim)

index_params = milvus_client.prepare_index_params()
index_params.add_index(field_name="embeddings", index_type="HNSW", metric_type="L2", M=30, efConstruction=200)
index_params.add_index(field_name="embeddings2", index_type="IVF_SQ8", metric_type="L2", nlist=64)


async def prepare_collection():
    for c in milvus_client.list_collections():
        log.info(f"Start dropping collection {c}")
        await async_milvus_client.drop_collection(c)
        log.info(f"Dropping collection {c} done")

    log.info("Start creating collection")
    await async_milvus_client.create_collection(collection_name, schema=schema, index_params=index_params, consistency_level="Strong")
    log.info("Creating collection done")


loop.run_until_complete(prepare_collection())
log.info(f"    all collections: {milvus_client.list_collections()}")
log.info(f"schema of collection {collection_name}")
log.info(milvus_client.describe_collection(collection_name))
```

- logs
```
python3 async_debug.py 
2024-12-18 16:49:23,707 [DEBUG][_create_connection]: Created new connection using: 11c97741be2849a2b0ae129f381f08f9 (async_milvus_client.py:546)
[2024-12-18 16:49:23,715 - INFO - async_test]: Start creating collection (async_debug.py:55)
2024-12-18 16:49:23,725 [DEBUG][_create_collection_with_schema]: Successfully created collection: hello_milvus (async_milvus_client.py:146)
2024-12-18 16:49:23,746 [DEBUG][_create_index]: Successfully created an index on collection: hello_milvus (async_milvus_client.py:199)
2024-12-18 16:49:23,765 [DEBUG][_create_index]: Successfully created an index on collection: hello_milvus (async_milvus_client.py:199)
[2024-12-18 16:49:23,778 - INFO - async_test]: Creating collection done (async_debug.py:57)
[2024-12-18 16:49:23,785 - INFO - async_test]:     all collections: [] (async_debug.py:61)
[2024-12-18 16:49:23,785 - INFO - async_test]: schema of collection hello_milvus (async_debug.py:62)
2024-12-18 16:49:23,793 [ERROR][handler]: RPC error: [describe_collection], <DescribeCollectionException: (code=100, message=can't find collection[database=zong][collection=hello_milvus])>, <Time:{'RPC start': '2024-12-18 16:49:23.785686', 'RPC error': '2024-12-18 16:49:23.793145'}> (decorators.py:145)
Traceback (most recent call last):
  File "/home/zong/PycharmProjects/async-test/async_debug.py", line 63, in <module>
    log.info(milvus_client.describe_collection(collection_name))
  File "/home/zong/PycharmProjects/async-test/venv/lib/python3.9/site-packages/pymilvus/milvus_client/milvus_client.py", line 644, in describe_collection
    return conn.describe_collection(collection_name, timeout=timeout, **kwargs)
  File "/home/zong/PycharmProjects/async-test/venv/lib/python3.9/site-packages/pymilvus/decorators.py", line 146, in handler
    raise e from e
  File "/home/zong/PycharmProjects/async-test/venv/lib/python3.9/site-packages/pymilvus/decorators.py", line 142, in handler
    return func(*args, **kwargs)
  File "/home/zong/PycharmProjects/async-test/venv/lib/python3.9/site-packages/pymilvus/decorators.py", line 181, in handler
    return func(self, *args, **kwargs)
  File "/home/zong/PycharmProjects/async-test/venv/lib/python3.9/site-packages/pymilvus/decorators.py", line 121, in handler
    raise e from e
  File "/home/zong/PycharmProjects/async-test/venv/lib/python3.9/site-packages/pymilvus/decorators.py", line 87, in handler
    return func(*args, **kwargs)
  File "/home/zong/PycharmProjects/async-test/venv/lib/python3.9/site-packages/pymilvus/client/grpc_handler.py", line 398, in describe_collection
    raise DescribeCollectionException(status.code, status.reason, status.error_code)
pymilvus.exceptions.DescribeCollectionException: <DescribeCollectionException: (code=100, message=can't find collection[database=zong][collection=hello_milvus])>
```

### Environment details

```markdown
- Hardware/Softward conditions (OS, CPU, GPU, Memory):
- Method of installation (Docker, or from source):
- Milvus version (v0.3.1, or v0.4.0):
- Milvus configuration (Settings you made in `server_config.yaml`):
```

**Comment by ThreadDao** [comment]
pymilvus==2.6.0rc27
