### ISSUE TITLE
[Bug]: AsyncMilvusClient create_collection without schema: 'AsyncGrpcHandler' object has no attribute 'async_create_collection'

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/pymilvus#2469]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

1. init AsyncMilvusClient
2. AsyncMilvusClient create collection without schema and gets error:
```
2024-12-18 16:56:30,750 [ERROR][_fast_create_collection]: Failed to create collection: hello_milvus (async_milvus_client.py:123)
Traceback (most recent call last):
  File "/home/zong/PycharmProjects/async-test/async_debug.py", line 55, in <module>
    loop.run_until_complete(prepare_collection())
  File "/usr/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/home/zong/PycharmProjects/async-test/async_debug.py", line 50, in prepare_collection
    await async_milvus_client.create_collection(collection_name, dimension=128, consistency_level="Strong")
  File "/home/zong/PycharmProjects/async-test/venv/lib/python3.9/site-packages/pymilvus/milvus_client/async_milvus_client.py", line 64, in create_collection
    return await self._fast_create_collection(
  File "/home/zong/PycharmProjects/async-test/venv/lib/python3.9/site-packages/pymilvus/milvus_client/async_milvus_client.py", line 124, in _fast_create_collection
    raise ex from ex
  File "/home/zong/PycharmProjects/async-test/venv/lib/python3.9/site-packages/pymilvus/milvus_client/async_milvus_client.py", line 120, in _fast_create_collection
    await conn.async_create_collection(collection_name, schema, timeout=timeout, **kwargs)
AttributeError: 'AsyncGrpcHandler' object has no attribute 'async_create_collection'
```

- case
```
from pymilvus import (
    DataType,
    MilvusClient,
    AsyncMilvusClient,
)
import numpy as np
import asyncio
from util_log import test_log as log

#
num_entities, dim = 10000, 128
nq, default_limit = 2, 3
collection_name = "hello_milvus"
rng = np.random.default_rng(seed=19530)
output_fields = ["pk", "random"]

uri = "http://10.104.17.186:19530"
db_name = "zong"
_client = MilvusClient(uri=uri)
if db_name not in _client.list_databases():
    _client.create_database(db_name)

_client.close()
milvus_client = MilvusClient(uri=uri)
async_milvus_client = AsyncMilvusClient(uri=uri)

loop = asyncio.get_event_loop()


# prepare collection
async def prepare_collection():
    for c in milvus_client.list_collections():
        log.info(f"Start dropping collection {c}")
        await async_milvus_client.drop_collection(c)
        log.info(f"Dropping collection {c} done")

    log.info("Start creating collection")
    await async_milvus_client.create_collection(collection_name, dimension=128, consistency_level="Strong")
    log.info("Creating collection done")
    await async_milvus_client.load_collection(collection_name)


loop.run_until_complete(prepare_collection())
log.info(f"    all collections: {milvus_client.list_collections()}")
log.info(f"schema of collection {collection_name}")
log.info(milvus_client.describe_collection(collection_name))


```

### Environment details

```markdown
- Hardware/Softward conditions (OS, CPU, GPU, Memory):
- Method of installation (Docker, or from source):
- Milvus version (v0.3.1, or v0.4.0):
- Milvus configuration (Settings you made in `server_config.yaml`):
```

**Comment by ThreadDao** [comment]
pymilvus==2.6.0rc27
