### ISSUE TITLE
[Bug]: AsyncMilvusClient failed to connect zillizcloud with uri and token

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/pymilvus#2475]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

uri = "https://in01-12d6e643fc0f514.aws-us-west-2.vectordb-uat3.zillizcloud.com:19534"
token = "6aff23xxxba25fa4"

milvus_client = MilvusClient(uri=uri,token=token)
async_milvus_client = AsyncMilvusClient(uri=uri,token=token)

error:
```
2024-12-18 14:04:33,498 [ERROR][handler]: grpc RpcError: [__internal_register], <AioRpcError: StatusCode.UNAUTHENTICATED, missing authorization in header>, <Time:{'RPC start': '2024-12-18 14:04:33.362641', 'gRPC error': '2024-12-18 14:04:33.498419'}> (decorators.py:156)
2024-12-18 14:04:33,498 [ERROR][_create_connection]: Failed to create new connection using: a39c46be46934e55b5d230eb855e124f (async_milvus_client.py:543)
Traceback (most recent call last):
  File "/home/zong/PycharmProjects/async-test/async_defaut.py", line 26, in <module>
    async_milvus_client = AsyncMilvusClient(uri=uri,token=token)
  File "/home/zong/PycharmProjects/async-test/venv/lib/python3.9/site-packages/pymilvus/milvus_client/async_milvus_client.py", line 44, in __init__
    self._using = self._create_connection(
  File "/home/zong/PycharmProjects/async-test/venv/lib/python3.9/site-packages/pymilvus/milvus_client/async_milvus_client.py", line 544, in _create_connection
    raise ex from ex
  File "/home/zong/PycharmProjects/async-test/venv/lib/python3.9/site-packages/pymilvus/milvus_client/async_milvus_client.py", line 539, in _create_connection
    connections.connect(
  File "/home/zong/PycharmProjects/async-test/venv/lib/python3.9/site-packages/pymilvus/orm/connections.py", line 452, in connect
    connect_milvus(**kwargs, user=user, password=password, token=token, db_name=db_name)
  File "/home/zong/PycharmProjects/async-test/venv/lib/python3.9/site-packages/pymilvus/orm/connections.py", line 403, in connect_milvus
    gh._wait_for_channel_ready(timeout=timeout)
  File "/home/zong/PycharmProjects/async-test/venv/lib/python3.9/site-packages/pymilvus/client/async_grpc_handler.py", line 127, in _wait_for_channel_ready
    raise e from e
  File "/home/zong/PycharmProjects/async-test/venv/lib/python3.9/site-packages/pymilvus/client/async_grpc_handler.py", line 120, in _wait_for_channel_ready
    self._setup_identifier_interceptor(self._user, timeout=timeout)
  File "/home/zong/PycharmProjects/async-test/venv/lib/python3.9/site-packages/pymilvus/client/async_grpc_handler.py", line 225, in _setup_identifier_interceptor
    self._identifier = self.__internal_register(user, host, timeout=timeout)
  File "/home/zong/PycharmProjects/async-test/venv/lib/python3.9/site-packages/pymilvus/decorators.py", line 160, in handler
    raise e from e
  File "/home/zong/PycharmProjects/async-test/venv/lib/python3.9/site-packages/pymilvus/decorators.py", line 142, in handler
    return func(*args, **kwargs)
  File "/home/zong/PycharmProjects/async-test/venv/lib/python3.9/site-packages/pymilvus/decorators.py", line 181, in handler
    return func(self, *args, **kwargs)
  File "/home/zong/PycharmProjects/async-test/venv/lib/python3.9/site-packages/pymilvus/decorators.py", line 91, in handler
    raise e from e
  File "/home/zong/PycharmProjects/async-test/venv/lib/python3.9/site-packages/pymilvus/decorators.py", line 87, in handler
    return func(*args, **kwargs)
  File "/home/zong/PycharmProjects/async-test/venv/lib/python3.9/site-packages/pymilvus/decorators.py", line 219, in handler
    raise e from e
  File "/home/zong/PycharmProjects/async-test/venv/lib/python3.9/site-packages/pymilvus/decorators.py", line 211, in handler
    return func(*args, **kwargs)
  File "/home/zong/PycharmProjects/async-test/venv/lib/python3.9/site-packages/pymilvus/client/async_grpc_handler.py", line 693, in __internal_register
    response = loop.run_until_complete(wait_for_connect_response())
  File "/usr/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/home/zong/PycharmProjects/async-test/venv/lib/python3.9/site-packages/pymilvus/client/async_grpc_handler.py", line 690, in wait_for_connect_response
    return await self._async_stub.Connect(request=req)
  File "/home/zong/PycharmProjects/async-test/venv/lib/python3.9/site-packages/grpc/aio/_call.py", line 318, in __await__
    raise _create_rpc_error(
grpc.aio._call.AioRpcError: <AioRpcError of RPC that terminated with:
        status = StatusCode.UNAUTHENTICATED
        details = "missing authorization in header"
        debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"missing authorization in header", grpc_status:16, created_time:"2024-12-18T14:04:33.497619596+08:00"}"
>
```

### Environment details

```markdown
- Hardware/Softward conditions (OS, CPU, GPU, Memory):
- Method of installation (Docker, or from source):
- Milvus version (v0.3.1, or v0.4.0):
- Milvus configuration (Settings you made in `server_config.yaml`):
```

**Comment by ThreadDao** [comment]
fixed:
pymilvus 2.4.11rc16
pymilvus==2.6.0rc26
