### ISSUE TITLE
[QUESTION] Trying to install Milvus Python SDK using pip3 to get pymilvus on AWS EC2, ERROR

### ISSUE THREAD

**Issue by alex-shmyga** [milvus-io/pymilvus#493]
**What is your question?**
Trying to install Milvus Python SDK using `pip3 to get pymilvus` on AWS EC2

```
Collecting pymilvus
  Downloading https://files.pythonhosted.org/packages/83/21/9228abb2bcef23aca28c7778785f545a51f0c3948906ad4858f6                                                                                                                    b417afeb/pymilvus-1.0.1-py3-none-any.whl (55kB)
    100% |████████████████████████████████| 61kB 7.3MB/s
Collecting ujson>=1.35 (from pymilvus)
  Downloading https://files.pythonhosted.org/packages/17/4e/50e8e4cf5f00b537095711c2c86ac4d7191aed2b4fffd5a19f06                                                                                                                    898f6929/ujson-4.0.2-cp37-cp37m-manylinux1_x86_64.whl (179kB)
    100% |████████████████████████████████| 184kB 5.6MB/s
Collecting grpcio>=1.22.0 (from pymilvus)
  Downloading https://files.pythonhosted.org/packages/0c/c5/f38a7ec5966b2d3b38488494213deaeec421aeef0ba6559e15f5                                                                                                                    8286416c/grpcio-1.37.0.tar.gz (21.7MB)
    100% |████████████████████████████████| 21.7MB 61kB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-1dfmk7iz/grpcio/setup.py", line 255, in <module>
        if check_linker_need_libatomic():
      File "/tmp/pip-build-1dfmk7iz/grpcio/setup.py", line 205, in check_linker_need_libatomic
        stderr=PIPE)
      File "/usr/lib64/python3.7/subprocess.py", line 800, in __init__
        restore_signals, start_new_session)
      File "/usr/lib64/python3.7/subprocess.py", line 1551, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    FileNotFoundError: [Errno 2] No such file or directory: 'c++': 'c++'

```

Any idea how to fix that?

**Comment by XuanYang-cn** [comment]
@alex-shmyga It seems your AWS EC2 need some thing more to build grpcio

```
dnf install gcc-c++ python3-devel
```
 or

```
sudo apt install build-essential
sudo apt install python-dev
```

**Comment by alex-shmyga** [comment]
Thanks, @XuanYang-cn , I fixed the original problem with this commands:
```
yum install gcc-c++.x86_64
yum install -y python3-pip python3 python3-setuptools
pip3 install --upgrade setuptools
```


however later I got this one
```

Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-4gpfzfh5/grpcio/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-e16b27bp-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-4gpfzfh5/grpcio/

```

**Comment by XuanYang-cn** [comment]
@alex-shmyga  try this

> Problem is with setuptools. Downgrade it to 49.6.0 and try installing it will work.

**Comment by alex-shmyga** [comment]
downgrade helped. Thanks, @XuanYang-cn
