### ISSUE TITLE
[BUG] Load interface does not support _async paramter

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/pymilvus#702]
**Describe the bug**
```
[2021-09-09 16:15:23,601 - DEBUG - ci_test]: (api_request)  : [Collection.load] args: [None], kwargs: {'_async': True, 'timeout': 20} (api_request.py:44)
[2021-09-09 16:15:23,603 - ERROR - ci_test]: Traceback (most recent call last):
  File "/home/zong/zong/projects/milvus/tests/python_client/utils/api_request.py", line 18, in inner_wrapper
    res = func(*args, **kwargs)
  File "/home/zong/zong/projects/milvus/tests/python_client/utils/api_request.py", line 45, in api_request
    return func(*arg, **kwargs)
  File "/home/zong/zong/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/orm/pymilvus_orm/collection.py", line 445, in load
    conn.load_collection(self._name, timeout=timeout, **kwargs)
  File "/home/zong/zong/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/client/stub.py", line 60, in handler
    raise e
  File "/home/zong/zong/.virtualenvs/milvus/lib/python3.8/site-packages/pymilvus/client/stub.py", line 44, in handler
    return func(self, *args, **kwargs)
TypeError: load_collection() got an unexpected keyword argument '_async'
 (api_request.py:26)
[2021-09-09 16:15:23,604 - ERROR - ci_test]: (api_response) : load_collection() got an unexpected keyword argument '_async' (api_request.py:27)
```

**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

**Environment details**

- Hardware/Softward conditions (OS, CPU, GPU, Memory)
- Method of installation (Docker, or from source)
- Milvus version (v0.3.1, or v0.4.0)
  pymilvus              2.0.0rc6.dev11
- Milvus configuration (Settings you made in `server_config.yaml`)

**Screenshots**

**Additional context**

**Comment by XuanYang-cn** [comment]
/unassign @Bennu-Li 
/assign @ThreadDao 

Should be fixed

**Comment by ThreadDao** [comment]
It fixed.
