### ISSUE TITLE
[Bug]: Search Freezes On 10 Million Vectors

### ISSUE THREAD

**Issue by Kencho5** [milvus-io/pymilvus#876]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

inserting and searching works as expected. i insert 512 dimensional vectors inside Milvus and create **IVF_SQ8** index on vectors (index is created before inserting). searching works fast and returns correct results until total vectors inside database reach around 10 million. after it reaches 10 million it freezes forever. 

i create index using:
```python
collection.create_index(field_name="vector",
                        index_params={'index_type': 'IVF_SQ8',
                                      'metric_type': 'L2',
                                      'params': {
                                        'nlist': 100      # int. 1~65536
                                      }})
collection.load()
```

search parameters:
```python
search_param = {
                "data": query_vectors,
                "anns_field": "vector",
                "param": {"metric_type": "L2", "params": {"nprobe": 8}},
                "limit": 5}
query_results = collection.search(**search_param)
```
traceback when i cancel when it freezes searching:
```
Traceback (most recent call last):
  File "search.py", line 41, in <module>
    query_results = collection.search(**search_param)
  File "/home/kencho/.local/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 697, in search
    res = conn.search(self._name, data, anns_field, param, limit, expr,
  File "/home/kencho/.local/lib/python3.8/site-packages/pymilvus/decorators.py", line 41, in handler
    return func(self, *args, **kwargs)
  File "/home/kencho/.local/lib/python3.8/site-packages/pymilvus/decorators.py", line 70, in handler
    return func(*args, **kwargs)
  File "/home/kencho/.local/lib/python3.8/site-packages/pymilvus/decorators.py", line 21, in handler
    return func(self, *args, **kwargs)
  File "/home/kencho/.local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 444, in search
    return self._execute_search_requests(requests, timeout, **_kwargs)
  File "/home/kencho/.local/lib/python3.8/site-packages/pymilvus/decorators.py", line 70, in handler
    return func(*args, **kwargs)
  File "/home/kencho/.local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 379, in _execute_search_requests
    response = ft.result()
  File "/home/kencho/.local/lib/python3.8/site-packages/grpc/_channel.py", line 733, in result
    timed_out = _common.wait(self._state.condition.wait,
  File "/home/kencho/.local/lib/python3.8/site-packages/grpc/_common.py", line 141, in wait
    _wait_once(wait_fn, MAXIMUM_WAIT_TIMEOUT, spin_cb)
  File "/home/kencho/.local/lib/python3.8/site-packages/grpc/_common.py", line 106, in _wait_once
    wait_fn(timeout=timeout)
  File "/usr/lib/python3.8/threading.py", line 306, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
```

### Expected Behavior

before reaching 10 million vectors everything works, after reaching 10 million it doesn't. why could that be or how is that even not working?

### Environment details

```markdown
- Hardware/Softward conditions (OS, CPU, GPU, Memory):
- Method of installation (Docker, or from source):
- Milvus version (v0.3.1, or v0.4.0):
- Milvus configuration (Settings you made in `server_config.yaml`):
```

**Comment by XuanYang-cn** [comment]
@Kencho5  Are you using Milvus standalone or cluster? 
The information provided looks like a bug in the server-side or a deadlock on python multithreading, could you please provide the full Milvus server logs or more detailed python scripts?

**Comment by XuanYang-cn** [comment]
BTW, we just finished the Chinese New Year holiday, sorry for the late response and happy Chinese New Year!

**Comment by Kencho5** [comment]
the issue was i was not letting collection load fully, it does take quite some time and i saw it was in the milestone to speed it up. it'd be really awesome to see it speed up and i hope it gets implemented. happy Chinese New Year!
