### ISSUE TITLE
[Bug]: Insert with DataTypeNotSupportException

### ISSUE THREAD

**Issue by XuanYang-cn** [milvus-io/pymilvus#906]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

```
Traceback (most recent call last):
  File "ex_image.py", line 57, in <module>
    collection.insert(data1)
  File "/mnt/e/wsl2/ubuntu/my_project_env/lib/python3.7/site-packages/pymilvus/orm/collection.py", line 535, in insert
    if not self._check_insert_data_schema(data):
  File "/mnt/e/wsl2/ubuntu/my_project_env/lib/python3.7/site-packages/pymilvus/orm/collection.py", line 179, in _check_insert_data_schema
    infer_fields = parse_fields_from_data(data)
  File "/mnt/e/wsl2/ubuntu/my_project_env/lib/python3.7/site-packages/pymilvus/orm/schema.py", line 297, in parse_fields_from_data
    fields.append(FieldSchema("", d_type))
  File "/mnt/e/wsl2/ubuntu/my_project_env/lib/python3.7/site-packages/pymilvus/orm/schema.py", line 172, in __init__
    raise DataTypeNotSupportException(0, ExceptionsMessage.FieldDtype)
pymilvus.orm.exceptions.DataTypeNotSupportException: <DataTypeNotSupportException: (code=0, message=Field dtype must be of DataType)>

```

### Environment details

```markdown
- Hardware/Softward conditions (OS, CPU, GPU, Memory):
- Method of installation (Docker, or from source):
- Milvus version (v0.3.1, or v0.4.0):
- Milvus configuration (Settings you made in `server_config.yaml`):
```

**Comment by XuanYang-cn** [comment]
This exception is too ambiguous, need to refactor `pase_field_from_data`
