### ISSUE TITLE
[Bug]: Nightly failed for pymilvus==2.1.0.dev40

### ISSUE THREAD

**Issue by XuanYang-cn** [milvus-io/pymilvus#977]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

https://github.com/milvus-io/pymilvus/runs/6311437169?check_suite_focus=true

/assign
/kind bug

### Environment details

```markdown
- Hardware/Softward conditions (OS, CPU, GPU, Memory):
- Method of installation (Docker, or from source):
- Milvus version (v0.3.1, or v0.4.0):
- Milvus configuration (Settings you made in `server_config.yaml`):
```

**Comment by XuanYang-cn** [comment]
```
Traceback (most recent call last):
  File "examples/hello_milvus.py", line 34, in <module>
    connections.connect("default", host=HOST, port=19530, secure=True)
  File "/home/yangxuan/.virtualenvs/py36milvus/lib/python3.6/site-packages/pymilvus/orm/connections.py", line 183, in connect
    raise ConnectionConfigException(0, ExceptionsMessage.NoHostPort)
pymilvus.exceptions.ConnectionConfigException: <ConnectionConfigException: (code=0, message=connection configuration must contain 'host' and 'port'.)>
```
